project:
  type: website
  output-dir: docs
  preview:
    port: 4200
    browser: true
  render:
    - index_cleaned.qmd

website:
  site-url: https://bijans-projects.github.io/genomics-data-mining
  repo-url: https://github.com/Bijans-Projects/genomics-data-mining
  issue-url: https://github.com/Bijans-Projects/genomics-data-mining/issues/new/choose
  repo-actions: [edit, source, issue]
  search:
    show-item-context: tree
    type: overlay
  page-footer:
    left: |
      Made up
  title: "Bijans Projects"
  reader-mode: true
  navbar:
    left:
      - index_cleaned.qmd
    tools:
      - icon: github
        href: https://github.com/Bijans-Projects
        text: Bijans Projects GitHub

jupyter: pixi-kernel-python3

format:
  html:
    anchor-sections: true
    code-fold: show
    code-overflow: wrap
    code-tools: true
    respect-user-color-scheme: true
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    grid:
      body-width: 2000px
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true