# coding: utf-8

"""
    cBioPortal web Public API [Alpha]

    A web service for supplying JSON formatted data to cBioPortal clients. Please note that this API is currently in beta and subject to change.  # noqa: E501

    OpenAPI spec version: 1.0 (beta). Backwards compatibility will be maintained (after 1.0 release)
    Contact: cbioportal@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cbioportal
from cbioportal.api.copy_number_segments_api import CopyNumberSegmentsApi  # noqa: E501
from cbioportal.rest import ApiException


class TestCopyNumberSegmentsApi(unittest.TestCase):
    """CopyNumberSegmentsApi unit test stubs"""

    def setUp(self):
        self.api = CopyNumberSegmentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_fetch_copy_number_segments_using_post(self):
        """Test case for fetch_copy_number_segments_using_post

        """
        pass

    def test_get_copy_number_segments_in_sample_in_study_using_get(self):
        """Test case for get_copy_number_segments_in_sample_in_study_using_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
