# coding: utf-8

"""
    cBioPortal web Public API [Alpha]

    A web service for supplying JSON formatted data to cBioPortal clients. Please note that this API is currently in beta and subject to change.  # noqa: E501

    OpenAPI spec version: 1.0 (beta). Backwards compatibility will be maintained (after 1.0 release)
    Contact: cbioportal@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cbioportal
from cbioportal.api.namespace_attributes_api import NamespaceAttributesApi  # noqa: E501
from cbioportal.rest import ApiException


class TestNamespaceAttributesApi(unittest.TestCase):
    """NamespaceAttributesApi unit test stubs"""

    def setUp(self):
        self.api = NamespaceAttributesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_fetch_namespace_using_post(self):
        """Test case for fetch_namespace_using_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
