# coding: utf-8

"""
    cBioPortal web Public API [Alpha]

    A web service for supplying JSON formatted data to cBioPortal clients. Please note that this API is currently in beta and subject to change.  # noqa: E501

    OpenAPI spec version: 1.0 (beta). Backwards compatibility will be maintained (after 1.0 release)
    Contact: cbioportal@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cbioportal
from cbioportal.api.patients_api import PatientsApi  # noqa: E501
from cbioportal.rest import ApiException


class TestPatientsApi(unittest.TestCase):
    """PatientsApi unit test stubs"""

    def setUp(self):
        self.api = PatientsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_fetch_patients_using_post(self):
        """Test case for fetch_patients_using_post

        """
        pass

    def test_get_all_patients_in_study_using_get(self):
        """Test case for get_all_patients_in_study_using_get

        """
        pass

    def test_get_all_patients_using_get(self):
        """Test case for get_all_patients_using_get

        """
        pass

    def test_get_patient_in_study_using_get(self):
        """Test case for get_patient_in_study_using_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
