# coding: utf-8

"""
    cBioPortal web Public API [Alpha]

    A web service for supplying JSON formatted data to cBioPortal clients. Please note that this API is currently in beta and subject to change.  # noqa: E501

    OpenAPI spec version: 1.0 (beta). Backwards compatibility will be maintained (after 1.0 release)
    Contact: cbioportal@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cbioportal
from cbioportal.models.gene_panel_data_multiple_study_filter import GenePanelDataMultipleStudyFilter  # noqa: E501
from cbioportal.rest import ApiException


class TestGenePanelDataMultipleStudyFilter(unittest.TestCase):
    """GenePanelDataMultipleStudyFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGenePanelDataMultipleStudyFilter(self):
        """Test GenePanelDataMultipleStudyFilter"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cbioportal.models.gene_panel_data_multiple_study_filter.GenePanelDataMultipleStudyFilter()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
