# coding: utf-8

"""
    cBioPortal web Public API [Alpha]

    A web service for supplying JSON formatted data to cBioPortal clients. Please note that this API is currently in beta and subject to change.  # noqa: E501

    OpenAPI spec version: 1.0 (beta). Backwards compatibility will be maintained (after 1.0 release)
    Contact: cbioportal@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cbioportal
from cbioportal.api.molecular_profiles_api import MolecularProfilesApi  # noqa: E501
from cbioportal.rest import ApiException


class TestMolecularProfilesApi(unittest.TestCase):
    """MolecularProfilesApi unit test stubs"""

    def setUp(self):
        self.api = MolecularProfilesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_fetch_molecular_profiles_using_post(self):
        """Test case for fetch_molecular_profiles_using_post

        """
        pass

    def test_get_all_molecular_profiles_in_study_using_get(self):
        """Test case for get_all_molecular_profiles_in_study_using_get

        """
        pass

    def test_get_all_molecular_profiles_using_get(self):
        """Test case for get_all_molecular_profiles_using_get

        """
        pass

    def test_get_molecular_profile_using_get(self):
        """Test case for get_molecular_profile_using_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
