# coding: utf-8

"""
    cBioPortal web Public API [Alpha]

    A web service for supplying JSON formatted data to cBioPortal clients. Please note that this API is currently in beta and subject to change.  # noqa: E501

    OpenAPI spec version: 1.0 (beta). Backwards compatibility will be maintained (after 1.0 release)
    Contact: cbioportal@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cbioportal
from cbioportal.api.clinical_data_api import ClinicalDataApi  # noqa: E501
from cbioportal.rest import ApiException


class TestClinicalDataApi(unittest.TestCase):
    """ClinicalDataApi unit test stubs"""

    def setUp(self):
        self.api = ClinicalDataApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_fetch_all_clinical_data_in_study_using_post(self):
        """Test case for fetch_all_clinical_data_in_study_using_post

        """
        pass

    def test_fetch_clinical_data_using_post(self):
        """Test case for fetch_clinical_data_using_post

        """
        pass

    def test_get_all_clinical_data_in_study_using_get(self):
        """Test case for get_all_clinical_data_in_study_using_get

        """
        pass

    def test_get_all_clinical_data_of_patient_in_study_using_get(self):
        """Test case for get_all_clinical_data_of_patient_in_study_using_get

        """
        pass

    def test_get_all_clinical_data_of_sample_in_study_using_get(self):
        """Test case for get_all_clinical_data_of_sample_in_study_using_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
