# coding: utf-8

"""
    cBioPortal web Public API [Alpha]

    A web service for supplying JSON formatted data to cBioPortal clients. Please note that this API is currently in beta and subject to change.  # noqa: E501

    OpenAPI spec version: 1.0 (beta). Backwards compatibility will be maintained (after 1.0 release)
    Contact: cbioportal@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cbioportal
from cbioportal.api.molecular_data_api import MolecularDataApi  # noqa: E501
from cbioportal.rest import ApiException


class TestMolecularDataApi(unittest.TestCase):
    """MolecularDataApi unit test stubs"""

    def setUp(self):
        self.api = MolecularDataApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_fetch_all_molecular_data_in_molecular_profile_using_post(self):
        """Test case for fetch_all_molecular_data_in_molecular_profile_using_post

        """
        pass

    def test_fetch_molecular_data_in_multiple_molecular_profiles_using_post(self):
        """Test case for fetch_molecular_data_in_multiple_molecular_profiles_using_post

        """
        pass

    def test_get_all_molecular_data_in_molecular_profile_using_get(self):
        """Test case for get_all_molecular_data_in_molecular_profile_using_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
