{% set name = "cbioportal" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv --no-deps"

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools
  run:
    - python >=3.10
    - urllib3 >=1.15
    - six >=1.10
    - certifi
    - python-dateutil >=2.5.3

test:
  imports:
    - cbioportal

about:
  summary: "Swagger-generated Python client for the cBioPortal API"
  license: "UNKNOWN"
