# coding: utf-8

"""
    cBioPortal web Public API [Alpha]

    A web service for supplying JSON formatted data to cBioPortal clients. Please note that this API is currently in beta and subject to change.  # noqa: E501

    OpenAPI spec version: 1.0 (beta). Backwards compatibility will be maintained (after 1.0 release)
    Contact: cbioportal@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CancerStudy(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'description': 'str',
        'public_study': 'bool',
        'pmid': 'str',
        'citation': 'str',
        'groups': 'str',
        'status': 'int',
        'import_date': 'datetime',
        'all_sample_count': 'int',
        'sequenced_sample_count': 'int',
        'cna_sample_count': 'int',
        'mrna_rna_seq_sample_count': 'int',
        'mrna_rna_seq_v2_sample_count': 'int',
        'mrna_microarray_sample_count': 'int',
        'mi_rna_sample_count': 'int',
        'methylation_hm27_sample_count': 'int',
        'rppa_sample_count': 'int',
        'mass_spectrometry_sample_count': 'int',
        'complete_sample_count': 'int',
        'read_permission': 'bool',
        'treatment_count': 'int',
        'structural_variant_count': 'int',
        'resource_counts': 'list[ResourceCount]',
        'study_id': 'str',
        'cancer_type_id': 'str',
        'cancer_type': 'TypeOfCancer',
        'reference_genome': 'str'
    }

    attribute_map = {
        'name': 'name',
        'description': 'description',
        'public_study': 'publicStudy',
        'pmid': 'pmid',
        'citation': 'citation',
        'groups': 'groups',
        'status': 'status',
        'import_date': 'importDate',
        'all_sample_count': 'allSampleCount',
        'sequenced_sample_count': 'sequencedSampleCount',
        'cna_sample_count': 'cnaSampleCount',
        'mrna_rna_seq_sample_count': 'mrnaRnaSeqSampleCount',
        'mrna_rna_seq_v2_sample_count': 'mrnaRnaSeqV2SampleCount',
        'mrna_microarray_sample_count': 'mrnaMicroarraySampleCount',
        'mi_rna_sample_count': 'miRnaSampleCount',
        'methylation_hm27_sample_count': 'methylationHm27SampleCount',
        'rppa_sample_count': 'rppaSampleCount',
        'mass_spectrometry_sample_count': 'massSpectrometrySampleCount',
        'complete_sample_count': 'completeSampleCount',
        'read_permission': 'readPermission',
        'treatment_count': 'treatmentCount',
        'structural_variant_count': 'structuralVariantCount',
        'resource_counts': 'resourceCounts',
        'study_id': 'studyId',
        'cancer_type_id': 'cancerTypeId',
        'cancer_type': 'cancerType',
        'reference_genome': 'referenceGenome'
    }

    def __init__(self, name=None, description=None, public_study=None, pmid=None, citation=None, groups=None, status=None, import_date=None, all_sample_count=None, sequenced_sample_count=None, cna_sample_count=None, mrna_rna_seq_sample_count=None, mrna_rna_seq_v2_sample_count=None, mrna_microarray_sample_count=None, mi_rna_sample_count=None, methylation_hm27_sample_count=None, rppa_sample_count=None, mass_spectrometry_sample_count=None, complete_sample_count=None, read_permission=None, treatment_count=None, structural_variant_count=None, resource_counts=None, study_id=None, cancer_type_id=None, cancer_type=None, reference_genome=None):  # noqa: E501
        """CancerStudy - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._description = None
        self._public_study = None
        self._pmid = None
        self._citation = None
        self._groups = None
        self._status = None
        self._import_date = None
        self._all_sample_count = None
        self._sequenced_sample_count = None
        self._cna_sample_count = None
        self._mrna_rna_seq_sample_count = None
        self._mrna_rna_seq_v2_sample_count = None
        self._mrna_microarray_sample_count = None
        self._mi_rna_sample_count = None
        self._methylation_hm27_sample_count = None
        self._rppa_sample_count = None
        self._mass_spectrometry_sample_count = None
        self._complete_sample_count = None
        self._read_permission = None
        self._treatment_count = None
        self._structural_variant_count = None
        self._resource_counts = None
        self._study_id = None
        self._cancer_type_id = None
        self._cancer_type = None
        self._reference_genome = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if description is not None:
            self.description = description
        if public_study is not None:
            self.public_study = public_study
        if pmid is not None:
            self.pmid = pmid
        if citation is not None:
            self.citation = citation
        if groups is not None:
            self.groups = groups
        if status is not None:
            self.status = status
        if import_date is not None:
            self.import_date = import_date
        if all_sample_count is not None:
            self.all_sample_count = all_sample_count
        if sequenced_sample_count is not None:
            self.sequenced_sample_count = sequenced_sample_count
        if cna_sample_count is not None:
            self.cna_sample_count = cna_sample_count
        if mrna_rna_seq_sample_count is not None:
            self.mrna_rna_seq_sample_count = mrna_rna_seq_sample_count
        if mrna_rna_seq_v2_sample_count is not None:
            self.mrna_rna_seq_v2_sample_count = mrna_rna_seq_v2_sample_count
        if mrna_microarray_sample_count is not None:
            self.mrna_microarray_sample_count = mrna_microarray_sample_count
        if mi_rna_sample_count is not None:
            self.mi_rna_sample_count = mi_rna_sample_count
        if methylation_hm27_sample_count is not None:
            self.methylation_hm27_sample_count = methylation_hm27_sample_count
        if rppa_sample_count is not None:
            self.rppa_sample_count = rppa_sample_count
        if mass_spectrometry_sample_count is not None:
            self.mass_spectrometry_sample_count = mass_spectrometry_sample_count
        if complete_sample_count is not None:
            self.complete_sample_count = complete_sample_count
        if read_permission is not None:
            self.read_permission = read_permission
        if treatment_count is not None:
            self.treatment_count = treatment_count
        if structural_variant_count is not None:
            self.structural_variant_count = structural_variant_count
        if resource_counts is not None:
            self.resource_counts = resource_counts
        self.study_id = study_id
        if cancer_type_id is not None:
            self.cancer_type_id = cancer_type_id
        if cancer_type is not None:
            self.cancer_type = cancer_type
        if reference_genome is not None:
            self.reference_genome = reference_genome

    @property
    def name(self):
        """Gets the name of this CancerStudy.  # noqa: E501


        :return: The name of this CancerStudy.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CancerStudy.


        :param name: The name of this CancerStudy.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """Gets the description of this CancerStudy.  # noqa: E501


        :return: The description of this CancerStudy.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this CancerStudy.


        :param description: The description of this CancerStudy.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def public_study(self):
        """Gets the public_study of this CancerStudy.  # noqa: E501


        :return: The public_study of this CancerStudy.  # noqa: E501
        :rtype: bool
        """
        return self._public_study

    @public_study.setter
    def public_study(self, public_study):
        """Sets the public_study of this CancerStudy.


        :param public_study: The public_study of this CancerStudy.  # noqa: E501
        :type: bool
        """

        self._public_study = public_study

    @property
    def pmid(self):
        """Gets the pmid of this CancerStudy.  # noqa: E501


        :return: The pmid of this CancerStudy.  # noqa: E501
        :rtype: str
        """
        return self._pmid

    @pmid.setter
    def pmid(self, pmid):
        """Sets the pmid of this CancerStudy.


        :param pmid: The pmid of this CancerStudy.  # noqa: E501
        :type: str
        """

        self._pmid = pmid

    @property
    def citation(self):
        """Gets the citation of this CancerStudy.  # noqa: E501


        :return: The citation of this CancerStudy.  # noqa: E501
        :rtype: str
        """
        return self._citation

    @citation.setter
    def citation(self, citation):
        """Sets the citation of this CancerStudy.


        :param citation: The citation of this CancerStudy.  # noqa: E501
        :type: str
        """

        self._citation = citation

    @property
    def groups(self):
        """Gets the groups of this CancerStudy.  # noqa: E501


        :return: The groups of this CancerStudy.  # noqa: E501
        :rtype: str
        """
        return self._groups

    @groups.setter
    def groups(self, groups):
        """Sets the groups of this CancerStudy.


        :param groups: The groups of this CancerStudy.  # noqa: E501
        :type: str
        """

        self._groups = groups

    @property
    def status(self):
        """Gets the status of this CancerStudy.  # noqa: E501


        :return: The status of this CancerStudy.  # noqa: E501
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this CancerStudy.


        :param status: The status of this CancerStudy.  # noqa: E501
        :type: int
        """

        self._status = status

    @property
    def import_date(self):
        """Gets the import_date of this CancerStudy.  # noqa: E501


        :return: The import_date of this CancerStudy.  # noqa: E501
        :rtype: datetime
        """
        return self._import_date

    @import_date.setter
    def import_date(self, import_date):
        """Sets the import_date of this CancerStudy.


        :param import_date: The import_date of this CancerStudy.  # noqa: E501
        :type: datetime
        """

        self._import_date = import_date

    @property
    def all_sample_count(self):
        """Gets the all_sample_count of this CancerStudy.  # noqa: E501


        :return: The all_sample_count of this CancerStudy.  # noqa: E501
        :rtype: int
        """
        return self._all_sample_count

    @all_sample_count.setter
    def all_sample_count(self, all_sample_count):
        """Sets the all_sample_count of this CancerStudy.


        :param all_sample_count: The all_sample_count of this CancerStudy.  # noqa: E501
        :type: int
        """

        self._all_sample_count = all_sample_count

    @property
    def sequenced_sample_count(self):
        """Gets the sequenced_sample_count of this CancerStudy.  # noqa: E501


        :return: The sequenced_sample_count of this CancerStudy.  # noqa: E501
        :rtype: int
        """
        return self._sequenced_sample_count

    @sequenced_sample_count.setter
    def sequenced_sample_count(self, sequenced_sample_count):
        """Sets the sequenced_sample_count of this CancerStudy.


        :param sequenced_sample_count: The sequenced_sample_count of this CancerStudy.  # noqa: E501
        :type: int
        """

        self._sequenced_sample_count = sequenced_sample_count

    @property
    def cna_sample_count(self):
        """Gets the cna_sample_count of this CancerStudy.  # noqa: E501


        :return: The cna_sample_count of this CancerStudy.  # noqa: E501
        :rtype: int
        """
        return self._cna_sample_count

    @cna_sample_count.setter
    def cna_sample_count(self, cna_sample_count):
        """Sets the cna_sample_count of this CancerStudy.


        :param cna_sample_count: The cna_sample_count of this CancerStudy.  # noqa: E501
        :type: int
        """

        self._cna_sample_count = cna_sample_count

    @property
    def mrna_rna_seq_sample_count(self):
        """Gets the mrna_rna_seq_sample_count of this CancerStudy.  # noqa: E501


        :return: The mrna_rna_seq_sample_count of this CancerStudy.  # noqa: E501
        :rtype: int
        """
        return self._mrna_rna_seq_sample_count

    @mrna_rna_seq_sample_count.setter
    def mrna_rna_seq_sample_count(self, mrna_rna_seq_sample_count):
        """Sets the mrna_rna_seq_sample_count of this CancerStudy.


        :param mrna_rna_seq_sample_count: The mrna_rna_seq_sample_count of this CancerStudy.  # noqa: E501
        :type: int
        """

        self._mrna_rna_seq_sample_count = mrna_rna_seq_sample_count

    @property
    def mrna_rna_seq_v2_sample_count(self):
        """Gets the mrna_rna_seq_v2_sample_count of this CancerStudy.  # noqa: E501


        :return: The mrna_rna_seq_v2_sample_count of this CancerStudy.  # noqa: E501
        :rtype: int
        """
        return self._mrna_rna_seq_v2_sample_count

    @mrna_rna_seq_v2_sample_count.setter
    def mrna_rna_seq_v2_sample_count(self, mrna_rna_seq_v2_sample_count):
        """Sets the mrna_rna_seq_v2_sample_count of this CancerStudy.


        :param mrna_rna_seq_v2_sample_count: The mrna_rna_seq_v2_sample_count of this CancerStudy.  # noqa: E501
        :type: int
        """

        self._mrna_rna_seq_v2_sample_count = mrna_rna_seq_v2_sample_count

    @property
    def mrna_microarray_sample_count(self):
        """Gets the mrna_microarray_sample_count of this CancerStudy.  # noqa: E501


        :return: The mrna_microarray_sample_count of this CancerStudy.  # noqa: E501
        :rtype: int
        """
        return self._mrna_microarray_sample_count

    @mrna_microarray_sample_count.setter
    def mrna_microarray_sample_count(self, mrna_microarray_sample_count):
        """Sets the mrna_microarray_sample_count of this CancerStudy.


        :param mrna_microarray_sample_count: The mrna_microarray_sample_count of this CancerStudy.  # noqa: E501
        :type: int
        """

        self._mrna_microarray_sample_count = mrna_microarray_sample_count

    @property
    def mi_rna_sample_count(self):
        """Gets the mi_rna_sample_count of this CancerStudy.  # noqa: E501


        :return: The mi_rna_sample_count of this CancerStudy.  # noqa: E501
        :rtype: int
        """
        return self._mi_rna_sample_count

    @mi_rna_sample_count.setter
    def mi_rna_sample_count(self, mi_rna_sample_count):
        """Sets the mi_rna_sample_count of this CancerStudy.


        :param mi_rna_sample_count: The mi_rna_sample_count of this CancerStudy.  # noqa: E501
        :type: int
        """

        self._mi_rna_sample_count = mi_rna_sample_count

    @property
    def methylation_hm27_sample_count(self):
        """Gets the methylation_hm27_sample_count of this CancerStudy.  # noqa: E501


        :return: The methylation_hm27_sample_count of this CancerStudy.  # noqa: E501
        :rtype: int
        """
        return self._methylation_hm27_sample_count

    @methylation_hm27_sample_count.setter
    def methylation_hm27_sample_count(self, methylation_hm27_sample_count):
        """Sets the methylation_hm27_sample_count of this CancerStudy.


        :param methylation_hm27_sample_count: The methylation_hm27_sample_count of this CancerStudy.  # noqa: E501
        :type: int
        """

        self._methylation_hm27_sample_count = methylation_hm27_sample_count

    @property
    def rppa_sample_count(self):
        """Gets the rppa_sample_count of this CancerStudy.  # noqa: E501


        :return: The rppa_sample_count of this CancerStudy.  # noqa: E501
        :rtype: int
        """
        return self._rppa_sample_count

    @rppa_sample_count.setter
    def rppa_sample_count(self, rppa_sample_count):
        """Sets the rppa_sample_count of this CancerStudy.


        :param rppa_sample_count: The rppa_sample_count of this CancerStudy.  # noqa: E501
        :type: int
        """

        self._rppa_sample_count = rppa_sample_count

    @property
    def mass_spectrometry_sample_count(self):
        """Gets the mass_spectrometry_sample_count of this CancerStudy.  # noqa: E501


        :return: The mass_spectrometry_sample_count of this CancerStudy.  # noqa: E501
        :rtype: int
        """
        return self._mass_spectrometry_sample_count

    @mass_spectrometry_sample_count.setter
    def mass_spectrometry_sample_count(self, mass_spectrometry_sample_count):
        """Sets the mass_spectrometry_sample_count of this CancerStudy.


        :param mass_spectrometry_sample_count: The mass_spectrometry_sample_count of this CancerStudy.  # noqa: E501
        :type: int
        """

        self._mass_spectrometry_sample_count = mass_spectrometry_sample_count

    @property
    def complete_sample_count(self):
        """Gets the complete_sample_count of this CancerStudy.  # noqa: E501


        :return: The complete_sample_count of this CancerStudy.  # noqa: E501
        :rtype: int
        """
        return self._complete_sample_count

    @complete_sample_count.setter
    def complete_sample_count(self, complete_sample_count):
        """Sets the complete_sample_count of this CancerStudy.


        :param complete_sample_count: The complete_sample_count of this CancerStudy.  # noqa: E501
        :type: int
        """

        self._complete_sample_count = complete_sample_count

    @property
    def read_permission(self):
        """Gets the read_permission of this CancerStudy.  # noqa: E501


        :return: The read_permission of this CancerStudy.  # noqa: E501
        :rtype: bool
        """
        return self._read_permission

    @read_permission.setter
    def read_permission(self, read_permission):
        """Sets the read_permission of this CancerStudy.


        :param read_permission: The read_permission of this CancerStudy.  # noqa: E501
        :type: bool
        """

        self._read_permission = read_permission

    @property
    def treatment_count(self):
        """Gets the treatment_count of this CancerStudy.  # noqa: E501


        :return: The treatment_count of this CancerStudy.  # noqa: E501
        :rtype: int
        """
        return self._treatment_count

    @treatment_count.setter
    def treatment_count(self, treatment_count):
        """Sets the treatment_count of this CancerStudy.


        :param treatment_count: The treatment_count of this CancerStudy.  # noqa: E501
        :type: int
        """

        self._treatment_count = treatment_count

    @property
    def structural_variant_count(self):
        """Gets the structural_variant_count of this CancerStudy.  # noqa: E501


        :return: The structural_variant_count of this CancerStudy.  # noqa: E501
        :rtype: int
        """
        return self._structural_variant_count

    @structural_variant_count.setter
    def structural_variant_count(self, structural_variant_count):
        """Sets the structural_variant_count of this CancerStudy.


        :param structural_variant_count: The structural_variant_count of this CancerStudy.  # noqa: E501
        :type: int
        """

        self._structural_variant_count = structural_variant_count

    @property
    def resource_counts(self):
        """Gets the resource_counts of this CancerStudy.  # noqa: E501


        :return: The resource_counts of this CancerStudy.  # noqa: E501
        :rtype: list[ResourceCount]
        """
        return self._resource_counts

    @resource_counts.setter
    def resource_counts(self, resource_counts):
        """Sets the resource_counts of this CancerStudy.


        :param resource_counts: The resource_counts of this CancerStudy.  # noqa: E501
        :type: list[ResourceCount]
        """

        self._resource_counts = resource_counts

    @property
    def study_id(self):
        """Gets the study_id of this CancerStudy.  # noqa: E501


        :return: The study_id of this CancerStudy.  # noqa: E501
        :rtype: str
        """
        return self._study_id

    @study_id.setter
    def study_id(self, study_id):
        """Sets the study_id of this CancerStudy.


        :param study_id: The study_id of this CancerStudy.  # noqa: E501
        :type: str
        """
        if study_id is None:
            raise ValueError("Invalid value for `study_id`, must not be `None`")  # noqa: E501

        self._study_id = study_id

    @property
    def cancer_type_id(self):
        """Gets the cancer_type_id of this CancerStudy.  # noqa: E501


        :return: The cancer_type_id of this CancerStudy.  # noqa: E501
        :rtype: str
        """
        return self._cancer_type_id

    @cancer_type_id.setter
    def cancer_type_id(self, cancer_type_id):
        """Sets the cancer_type_id of this CancerStudy.


        :param cancer_type_id: The cancer_type_id of this CancerStudy.  # noqa: E501
        :type: str
        """

        self._cancer_type_id = cancer_type_id

    @property
    def cancer_type(self):
        """Gets the cancer_type of this CancerStudy.  # noqa: E501


        :return: The cancer_type of this CancerStudy.  # noqa: E501
        :rtype: TypeOfCancer
        """
        return self._cancer_type

    @cancer_type.setter
    def cancer_type(self, cancer_type):
        """Sets the cancer_type of this CancerStudy.


        :param cancer_type: The cancer_type of this CancerStudy.  # noqa: E501
        :type: TypeOfCancer
        """

        self._cancer_type = cancer_type

    @property
    def reference_genome(self):
        """Gets the reference_genome of this CancerStudy.  # noqa: E501


        :return: The reference_genome of this CancerStudy.  # noqa: E501
        :rtype: str
        """
        return self._reference_genome

    @reference_genome.setter
    def reference_genome(self, reference_genome):
        """Sets the reference_genome of this CancerStudy.


        :param reference_genome: The reference_genome of this CancerStudy.  # noqa: E501
        :type: str
        """

        self._reference_genome = reference_genome

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CancerStudy, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CancerStudy):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
