# coding: utf-8

"""
    cBioPortal web Public API [Alpha]

    A web service for supplying JSON formatted data to cBioPortal clients. Please note that this API is currently in beta and subject to change.  # noqa: E501

    OpenAPI spec version: 1.0 (beta). Backwards compatibility will be maintained (after 1.0 release)
    Contact: cbioportal@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CancerStudyTags(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'cancer_study_id': 'int',
        'study_id': 'str',
        'tags': 'str'
    }

    attribute_map = {
        'cancer_study_id': 'cancerStudyId',
        'study_id': 'studyId',
        'tags': 'tags'
    }

    def __init__(self, cancer_study_id=None, study_id=None, tags=None):  # noqa: E501
        """CancerStudyTags - a model defined in Swagger"""  # noqa: E501
        self._cancer_study_id = None
        self._study_id = None
        self._tags = None
        self.discriminator = None
        if cancer_study_id is not None:
            self.cancer_study_id = cancer_study_id
        if study_id is not None:
            self.study_id = study_id
        if tags is not None:
            self.tags = tags

    @property
    def cancer_study_id(self):
        """Gets the cancer_study_id of this CancerStudyTags.  # noqa: E501


        :return: The cancer_study_id of this CancerStudyTags.  # noqa: E501
        :rtype: int
        """
        return self._cancer_study_id

    @cancer_study_id.setter
    def cancer_study_id(self, cancer_study_id):
        """Sets the cancer_study_id of this CancerStudyTags.


        :param cancer_study_id: The cancer_study_id of this CancerStudyTags.  # noqa: E501
        :type: int
        """

        self._cancer_study_id = cancer_study_id

    @property
    def study_id(self):
        """Gets the study_id of this CancerStudyTags.  # noqa: E501


        :return: The study_id of this CancerStudyTags.  # noqa: E501
        :rtype: str
        """
        return self._study_id

    @study_id.setter
    def study_id(self, study_id):
        """Sets the study_id of this CancerStudyTags.


        :param study_id: The study_id of this CancerStudyTags.  # noqa: E501
        :type: str
        """

        self._study_id = study_id

    @property
    def tags(self):
        """Gets the tags of this CancerStudyTags.  # noqa: E501


        :return: The tags of this CancerStudyTags.  # noqa: E501
        :rtype: str
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this CancerStudyTags.


        :param tags: The tags of this CancerStudyTags.  # noqa: E501
        :type: str
        """

        self._tags = tags

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CancerStudyTags, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CancerStudyTags):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
