# coding: utf-8

"""
    cBioPortal web Public API [Alpha]

    A web service for supplying JSON formatted data to cBioPortal clients. Please note that this API is currently in beta and subject to change.  # noqa: E501

    OpenAPI spec version: 1.0 (beta). Backwards compatibility will be maintained (after 1.0 release)
    Contact: cbioportal@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ClinicalDataIdentifier(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'entity_id': 'str',
        'study_id': 'str'
    }

    attribute_map = {
        'entity_id': 'entityId',
        'study_id': 'studyId'
    }

    def __init__(self, entity_id=None, study_id=None):  # noqa: E501
        """ClinicalDataIdentifier - a model defined in Swagger"""  # noqa: E501
        self._entity_id = None
        self._study_id = None
        self.discriminator = None
        if entity_id is not None:
            self.entity_id = entity_id
        if study_id is not None:
            self.study_id = study_id

    @property
    def entity_id(self):
        """Gets the entity_id of this ClinicalDataIdentifier.  # noqa: E501


        :return: The entity_id of this ClinicalDataIdentifier.  # noqa: E501
        :rtype: str
        """
        return self._entity_id

    @entity_id.setter
    def entity_id(self, entity_id):
        """Sets the entity_id of this ClinicalDataIdentifier.


        :param entity_id: The entity_id of this ClinicalDataIdentifier.  # noqa: E501
        :type: str
        """

        self._entity_id = entity_id

    @property
    def study_id(self):
        """Gets the study_id of this ClinicalDataIdentifier.  # noqa: E501


        :return: The study_id of this ClinicalDataIdentifier.  # noqa: E501
        :rtype: str
        """
        return self._study_id

    @study_id.setter
    def study_id(self, study_id):
        """Sets the study_id of this ClinicalDataIdentifier.


        :param study_id: The study_id of this ClinicalDataIdentifier.  # noqa: E501
        :type: str
        """

        self._study_id = study_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ClinicalDataIdentifier, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ClinicalDataIdentifier):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
