# coding: utf-8

"""
    cBioPortal web Public API [Alpha]

    A web service for supplying JSON formatted data to cBioPortal clients. Please note that this API is currently in beta and subject to change.  # noqa: E501

    OpenAPI spec version: 1.0 (beta). Backwards compatibility will be maintained (after 1.0 release)
    Contact: cbioportal@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ClinicalData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'unique_sample_key': 'str',
        'unique_patient_key': 'str',
        'sample_id': 'str',
        'patient_id': 'str',
        'study_id': 'str',
        'clinical_attribute': 'ClinicalAttribute',
        'patient_attribute': 'bool',
        'clinical_attribute_id': 'str',
        'value': 'str'
    }

    attribute_map = {
        'unique_sample_key': 'uniqueSampleKey',
        'unique_patient_key': 'uniquePatientKey',
        'sample_id': 'sampleId',
        'patient_id': 'patientId',
        'study_id': 'studyId',
        'clinical_attribute': 'clinicalAttribute',
        'patient_attribute': 'patientAttribute',
        'clinical_attribute_id': 'clinicalAttributeId',
        'value': 'value'
    }

    def __init__(self, unique_sample_key=None, unique_patient_key=None, sample_id=None, patient_id=None, study_id=None, clinical_attribute=None, patient_attribute=None, clinical_attribute_id=None, value=None):  # noqa: E501
        """ClinicalData - a model defined in Swagger"""  # noqa: E501
        self._unique_sample_key = None
        self._unique_patient_key = None
        self._sample_id = None
        self._patient_id = None
        self._study_id = None
        self._clinical_attribute = None
        self._patient_attribute = None
        self._clinical_attribute_id = None
        self._value = None
        self.discriminator = None
        if unique_sample_key is not None:
            self.unique_sample_key = unique_sample_key
        if unique_patient_key is not None:
            self.unique_patient_key = unique_patient_key
        if sample_id is not None:
            self.sample_id = sample_id
        self.patient_id = patient_id
        self.study_id = study_id
        if clinical_attribute is not None:
            self.clinical_attribute = clinical_attribute
        if patient_attribute is not None:
            self.patient_attribute = patient_attribute
        self.clinical_attribute_id = clinical_attribute_id
        if value is not None:
            self.value = value

    @property
    def unique_sample_key(self):
        """Gets the unique_sample_key of this ClinicalData.  # noqa: E501


        :return: The unique_sample_key of this ClinicalData.  # noqa: E501
        :rtype: str
        """
        return self._unique_sample_key

    @unique_sample_key.setter
    def unique_sample_key(self, unique_sample_key):
        """Sets the unique_sample_key of this ClinicalData.


        :param unique_sample_key: The unique_sample_key of this ClinicalData.  # noqa: E501
        :type: str
        """

        self._unique_sample_key = unique_sample_key

    @property
    def unique_patient_key(self):
        """Gets the unique_patient_key of this ClinicalData.  # noqa: E501


        :return: The unique_patient_key of this ClinicalData.  # noqa: E501
        :rtype: str
        """
        return self._unique_patient_key

    @unique_patient_key.setter
    def unique_patient_key(self, unique_patient_key):
        """Sets the unique_patient_key of this ClinicalData.


        :param unique_patient_key: The unique_patient_key of this ClinicalData.  # noqa: E501
        :type: str
        """

        self._unique_patient_key = unique_patient_key

    @property
    def sample_id(self):
        """Gets the sample_id of this ClinicalData.  # noqa: E501


        :return: The sample_id of this ClinicalData.  # noqa: E501
        :rtype: str
        """
        return self._sample_id

    @sample_id.setter
    def sample_id(self, sample_id):
        """Sets the sample_id of this ClinicalData.


        :param sample_id: The sample_id of this ClinicalData.  # noqa: E501
        :type: str
        """

        self._sample_id = sample_id

    @property
    def patient_id(self):
        """Gets the patient_id of this ClinicalData.  # noqa: E501


        :return: The patient_id of this ClinicalData.  # noqa: E501
        :rtype: str
        """
        return self._patient_id

    @patient_id.setter
    def patient_id(self, patient_id):
        """Sets the patient_id of this ClinicalData.


        :param patient_id: The patient_id of this ClinicalData.  # noqa: E501
        :type: str
        """
        if patient_id is None:
            raise ValueError("Invalid value for `patient_id`, must not be `None`")  # noqa: E501

        self._patient_id = patient_id

    @property
    def study_id(self):
        """Gets the study_id of this ClinicalData.  # noqa: E501


        :return: The study_id of this ClinicalData.  # noqa: E501
        :rtype: str
        """
        return self._study_id

    @study_id.setter
    def study_id(self, study_id):
        """Sets the study_id of this ClinicalData.


        :param study_id: The study_id of this ClinicalData.  # noqa: E501
        :type: str
        """
        if study_id is None:
            raise ValueError("Invalid value for `study_id`, must not be `None`")  # noqa: E501

        self._study_id = study_id

    @property
    def clinical_attribute(self):
        """Gets the clinical_attribute of this ClinicalData.  # noqa: E501


        :return: The clinical_attribute of this ClinicalData.  # noqa: E501
        :rtype: ClinicalAttribute
        """
        return self._clinical_attribute

    @clinical_attribute.setter
    def clinical_attribute(self, clinical_attribute):
        """Sets the clinical_attribute of this ClinicalData.


        :param clinical_attribute: The clinical_attribute of this ClinicalData.  # noqa: E501
        :type: ClinicalAttribute
        """

        self._clinical_attribute = clinical_attribute

    @property
    def patient_attribute(self):
        """Gets the patient_attribute of this ClinicalData.  # noqa: E501


        :return: The patient_attribute of this ClinicalData.  # noqa: E501
        :rtype: bool
        """
        return self._patient_attribute

    @patient_attribute.setter
    def patient_attribute(self, patient_attribute):
        """Sets the patient_attribute of this ClinicalData.


        :param patient_attribute: The patient_attribute of this ClinicalData.  # noqa: E501
        :type: bool
        """

        self._patient_attribute = patient_attribute

    @property
    def clinical_attribute_id(self):
        """Gets the clinical_attribute_id of this ClinicalData.  # noqa: E501


        :return: The clinical_attribute_id of this ClinicalData.  # noqa: E501
        :rtype: str
        """
        return self._clinical_attribute_id

    @clinical_attribute_id.setter
    def clinical_attribute_id(self, clinical_attribute_id):
        """Sets the clinical_attribute_id of this ClinicalData.


        :param clinical_attribute_id: The clinical_attribute_id of this ClinicalData.  # noqa: E501
        :type: str
        """
        if clinical_attribute_id is None:
            raise ValueError("Invalid value for `clinical_attribute_id`, must not be `None`")  # noqa: E501

        self._clinical_attribute_id = clinical_attribute_id

    @property
    def value(self):
        """Gets the value of this ClinicalData.  # noqa: E501


        :return: The value of this ClinicalData.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this ClinicalData.


        :param value: The value of this ClinicalData.  # noqa: E501
        :type: str
        """

        self._value = value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ClinicalData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ClinicalData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
