# coding: utf-8

"""
    cBioPortal web Public API [Alpha]

    A web service for supplying JSON formatted data to cBioPortal clients. Please note that this API is currently in beta and subject to change.  # noqa: E501

    OpenAPI spec version: 1.0 (beta). Backwards compatibility will be maintained (after 1.0 release)
    Contact: cbioportal@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ClinicalAttribute(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'display_name': 'str',
        'description': 'str',
        'datatype': 'str',
        'patient_attribute': 'bool',
        'priority': 'str',
        'clinical_attribute_id': 'str',
        'study_id': 'str'
    }

    attribute_map = {
        'display_name': 'displayName',
        'description': 'description',
        'datatype': 'datatype',
        'patient_attribute': 'patientAttribute',
        'priority': 'priority',
        'clinical_attribute_id': 'clinicalAttributeId',
        'study_id': 'studyId'
    }

    def __init__(self, display_name=None, description=None, datatype=None, patient_attribute=None, priority=None, clinical_attribute_id=None, study_id=None):  # noqa: E501
        """ClinicalAttribute - a model defined in Swagger"""  # noqa: E501
        self._display_name = None
        self._description = None
        self._datatype = None
        self._patient_attribute = None
        self._priority = None
        self._clinical_attribute_id = None
        self._study_id = None
        self.discriminator = None
        self.display_name = display_name
        if description is not None:
            self.description = description
        if datatype is not None:
            self.datatype = datatype
        self.patient_attribute = patient_attribute
        if priority is not None:
            self.priority = priority
        self.clinical_attribute_id = clinical_attribute_id
        self.study_id = study_id

    @property
    def display_name(self):
        """Gets the display_name of this ClinicalAttribute.  # noqa: E501


        :return: The display_name of this ClinicalAttribute.  # noqa: E501
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """Sets the display_name of this ClinicalAttribute.


        :param display_name: The display_name of this ClinicalAttribute.  # noqa: E501
        :type: str
        """
        if display_name is None:
            raise ValueError("Invalid value for `display_name`, must not be `None`")  # noqa: E501

        self._display_name = display_name

    @property
    def description(self):
        """Gets the description of this ClinicalAttribute.  # noqa: E501


        :return: The description of this ClinicalAttribute.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ClinicalAttribute.


        :param description: The description of this ClinicalAttribute.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def datatype(self):
        """Gets the datatype of this ClinicalAttribute.  # noqa: E501


        :return: The datatype of this ClinicalAttribute.  # noqa: E501
        :rtype: str
        """
        return self._datatype

    @datatype.setter
    def datatype(self, datatype):
        """Sets the datatype of this ClinicalAttribute.


        :param datatype: The datatype of this ClinicalAttribute.  # noqa: E501
        :type: str
        """

        self._datatype = datatype

    @property
    def patient_attribute(self):
        """Gets the patient_attribute of this ClinicalAttribute.  # noqa: E501


        :return: The patient_attribute of this ClinicalAttribute.  # noqa: E501
        :rtype: bool
        """
        return self._patient_attribute

    @patient_attribute.setter
    def patient_attribute(self, patient_attribute):
        """Sets the patient_attribute of this ClinicalAttribute.


        :param patient_attribute: The patient_attribute of this ClinicalAttribute.  # noqa: E501
        :type: bool
        """
        if patient_attribute is None:
            raise ValueError("Invalid value for `patient_attribute`, must not be `None`")  # noqa: E501

        self._patient_attribute = patient_attribute

    @property
    def priority(self):
        """Gets the priority of this ClinicalAttribute.  # noqa: E501


        :return: The priority of this ClinicalAttribute.  # noqa: E501
        :rtype: str
        """
        return self._priority

    @priority.setter
    def priority(self, priority):
        """Sets the priority of this ClinicalAttribute.


        :param priority: The priority of this ClinicalAttribute.  # noqa: E501
        :type: str
        """

        self._priority = priority

    @property
    def clinical_attribute_id(self):
        """Gets the clinical_attribute_id of this ClinicalAttribute.  # noqa: E501


        :return: The clinical_attribute_id of this ClinicalAttribute.  # noqa: E501
        :rtype: str
        """
        return self._clinical_attribute_id

    @clinical_attribute_id.setter
    def clinical_attribute_id(self, clinical_attribute_id):
        """Sets the clinical_attribute_id of this ClinicalAttribute.


        :param clinical_attribute_id: The clinical_attribute_id of this ClinicalAttribute.  # noqa: E501
        :type: str
        """
        if clinical_attribute_id is None:
            raise ValueError("Invalid value for `clinical_attribute_id`, must not be `None`")  # noqa: E501

        self._clinical_attribute_id = clinical_attribute_id

    @property
    def study_id(self):
        """Gets the study_id of this ClinicalAttribute.  # noqa: E501


        :return: The study_id of this ClinicalAttribute.  # noqa: E501
        :rtype: str
        """
        return self._study_id

    @study_id.setter
    def study_id(self, study_id):
        """Sets the study_id of this ClinicalAttribute.


        :param study_id: The study_id of this ClinicalAttribute.  # noqa: E501
        :type: str
        """
        if study_id is None:
            raise ValueError("Invalid value for `study_id`, must not be `None`")  # noqa: E501

        self._study_id = study_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ClinicalAttribute, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ClinicalAttribute):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
