# coding: utf-8

"""
    cBioPortal web Public API [Alpha]

    A web service for supplying JSON formatted data to cBioPortal clients. Please note that this API is currently in beta and subject to change.  # noqa: E501

    OpenAPI spec version: 1.0 (beta). Backwards compatibility will be maintained (after 1.0 release)
    Contact: cbioportal@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ClinicalDataMultiStudyFilter(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'identifiers': 'list[ClinicalDataIdentifier]',
        'attribute_ids': 'list[str]'
    }

    attribute_map = {
        'identifiers': 'identifiers',
        'attribute_ids': 'attributeIds'
    }

    def __init__(self, identifiers=None, attribute_ids=None):  # noqa: E501
        """ClinicalDataMultiStudyFilter - a model defined in Swagger"""  # noqa: E501
        self._identifiers = None
        self._attribute_ids = None
        self.discriminator = None
        if identifiers is not None:
            self.identifiers = identifiers
        if attribute_ids is not None:
            self.attribute_ids = attribute_ids

    @property
    def identifiers(self):
        """Gets the identifiers of this ClinicalDataMultiStudyFilter.  # noqa: E501


        :return: The identifiers of this ClinicalDataMultiStudyFilter.  # noqa: E501
        :rtype: list[ClinicalDataIdentifier]
        """
        return self._identifiers

    @identifiers.setter
    def identifiers(self, identifiers):
        """Sets the identifiers of this ClinicalDataMultiStudyFilter.


        :param identifiers: The identifiers of this ClinicalDataMultiStudyFilter.  # noqa: E501
        :type: list[ClinicalDataIdentifier]
        """

        self._identifiers = identifiers

    @property
    def attribute_ids(self):
        """Gets the attribute_ids of this ClinicalDataMultiStudyFilter.  # noqa: E501


        :return: The attribute_ids of this ClinicalDataMultiStudyFilter.  # noqa: E501
        :rtype: list[str]
        """
        return self._attribute_ids

    @attribute_ids.setter
    def attribute_ids(self, attribute_ids):
        """Sets the attribute_ids of this ClinicalDataMultiStudyFilter.


        :param attribute_ids: The attribute_ids of this ClinicalDataMultiStudyFilter.  # noqa: E501
        :type: list[str]
        """

        self._attribute_ids = attribute_ids

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ClinicalDataMultiStudyFilter, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ClinicalDataMultiStudyFilter):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
