# coding: utf-8

"""
    cBioPortal web Public API [Alpha]

    A web service for supplying JSON formatted data to cBioPortal clients. Please note that this API is currently in beta and subject to change.  # noqa: E501

    OpenAPI spec version: 1.0 (beta). Backwards compatibility will be maintained (after 1.0 release)
    Contact: cbioportal@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CopyNumberSeg(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'unique_sample_key': 'str',
        'unique_patient_key': 'str',
        'patient_id': 'str',
        'start': 'int',
        'end': 'int',
        'segment_mean': 'float',
        'study_id': 'str',
        'sample_id': 'str',
        'chromosome': 'str',
        'number_of_probes': 'int'
    }

    attribute_map = {
        'unique_sample_key': 'uniqueSampleKey',
        'unique_patient_key': 'uniquePatientKey',
        'patient_id': 'patientId',
        'start': 'start',
        'end': 'end',
        'segment_mean': 'segmentMean',
        'study_id': 'studyId',
        'sample_id': 'sampleId',
        'chromosome': 'chromosome',
        'number_of_probes': 'numberOfProbes'
    }

    def __init__(self, unique_sample_key=None, unique_patient_key=None, patient_id=None, start=None, end=None, segment_mean=None, study_id=None, sample_id=None, chromosome=None, number_of_probes=None):  # noqa: E501
        """CopyNumberSeg - a model defined in Swagger"""  # noqa: E501
        self._unique_sample_key = None
        self._unique_patient_key = None
        self._patient_id = None
        self._start = None
        self._end = None
        self._segment_mean = None
        self._study_id = None
        self._sample_id = None
        self._chromosome = None
        self._number_of_probes = None
        self.discriminator = None
        if unique_sample_key is not None:
            self.unique_sample_key = unique_sample_key
        if unique_patient_key is not None:
            self.unique_patient_key = unique_patient_key
        self.patient_id = patient_id
        self.start = start
        self.end = end
        self.segment_mean = segment_mean
        self.study_id = study_id
        self.sample_id = sample_id
        self.chromosome = chromosome
        self.number_of_probes = number_of_probes

    @property
    def unique_sample_key(self):
        """Gets the unique_sample_key of this CopyNumberSeg.  # noqa: E501


        :return: The unique_sample_key of this CopyNumberSeg.  # noqa: E501
        :rtype: str
        """
        return self._unique_sample_key

    @unique_sample_key.setter
    def unique_sample_key(self, unique_sample_key):
        """Sets the unique_sample_key of this CopyNumberSeg.


        :param unique_sample_key: The unique_sample_key of this CopyNumberSeg.  # noqa: E501
        :type: str
        """

        self._unique_sample_key = unique_sample_key

    @property
    def unique_patient_key(self):
        """Gets the unique_patient_key of this CopyNumberSeg.  # noqa: E501


        :return: The unique_patient_key of this CopyNumberSeg.  # noqa: E501
        :rtype: str
        """
        return self._unique_patient_key

    @unique_patient_key.setter
    def unique_patient_key(self, unique_patient_key):
        """Sets the unique_patient_key of this CopyNumberSeg.


        :param unique_patient_key: The unique_patient_key of this CopyNumberSeg.  # noqa: E501
        :type: str
        """

        self._unique_patient_key = unique_patient_key

    @property
    def patient_id(self):
        """Gets the patient_id of this CopyNumberSeg.  # noqa: E501


        :return: The patient_id of this CopyNumberSeg.  # noqa: E501
        :rtype: str
        """
        return self._patient_id

    @patient_id.setter
    def patient_id(self, patient_id):
        """Sets the patient_id of this CopyNumberSeg.


        :param patient_id: The patient_id of this CopyNumberSeg.  # noqa: E501
        :type: str
        """
        if patient_id is None:
            raise ValueError("Invalid value for `patient_id`, must not be `None`")  # noqa: E501

        self._patient_id = patient_id

    @property
    def start(self):
        """Gets the start of this CopyNumberSeg.  # noqa: E501


        :return: The start of this CopyNumberSeg.  # noqa: E501
        :rtype: int
        """
        return self._start

    @start.setter
    def start(self, start):
        """Sets the start of this CopyNumberSeg.


        :param start: The start of this CopyNumberSeg.  # noqa: E501
        :type: int
        """
        if start is None:
            raise ValueError("Invalid value for `start`, must not be `None`")  # noqa: E501

        self._start = start

    @property
    def end(self):
        """Gets the end of this CopyNumberSeg.  # noqa: E501


        :return: The end of this CopyNumberSeg.  # noqa: E501
        :rtype: int
        """
        return self._end

    @end.setter
    def end(self, end):
        """Sets the end of this CopyNumberSeg.


        :param end: The end of this CopyNumberSeg.  # noqa: E501
        :type: int
        """
        if end is None:
            raise ValueError("Invalid value for `end`, must not be `None`")  # noqa: E501

        self._end = end

    @property
    def segment_mean(self):
        """Gets the segment_mean of this CopyNumberSeg.  # noqa: E501


        :return: The segment_mean of this CopyNumberSeg.  # noqa: E501
        :rtype: float
        """
        return self._segment_mean

    @segment_mean.setter
    def segment_mean(self, segment_mean):
        """Sets the segment_mean of this CopyNumberSeg.


        :param segment_mean: The segment_mean of this CopyNumberSeg.  # noqa: E501
        :type: float
        """
        if segment_mean is None:
            raise ValueError("Invalid value for `segment_mean`, must not be `None`")  # noqa: E501

        self._segment_mean = segment_mean

    @property
    def study_id(self):
        """Gets the study_id of this CopyNumberSeg.  # noqa: E501


        :return: The study_id of this CopyNumberSeg.  # noqa: E501
        :rtype: str
        """
        return self._study_id

    @study_id.setter
    def study_id(self, study_id):
        """Sets the study_id of this CopyNumberSeg.


        :param study_id: The study_id of this CopyNumberSeg.  # noqa: E501
        :type: str
        """
        if study_id is None:
            raise ValueError("Invalid value for `study_id`, must not be `None`")  # noqa: E501

        self._study_id = study_id

    @property
    def sample_id(self):
        """Gets the sample_id of this CopyNumberSeg.  # noqa: E501


        :return: The sample_id of this CopyNumberSeg.  # noqa: E501
        :rtype: str
        """
        return self._sample_id

    @sample_id.setter
    def sample_id(self, sample_id):
        """Sets the sample_id of this CopyNumberSeg.


        :param sample_id: The sample_id of this CopyNumberSeg.  # noqa: E501
        :type: str
        """
        if sample_id is None:
            raise ValueError("Invalid value for `sample_id`, must not be `None`")  # noqa: E501

        self._sample_id = sample_id

    @property
    def chromosome(self):
        """Gets the chromosome of this CopyNumberSeg.  # noqa: E501


        :return: The chromosome of this CopyNumberSeg.  # noqa: E501
        :rtype: str
        """
        return self._chromosome

    @chromosome.setter
    def chromosome(self, chromosome):
        """Sets the chromosome of this CopyNumberSeg.


        :param chromosome: The chromosome of this CopyNumberSeg.  # noqa: E501
        :type: str
        """
        if chromosome is None:
            raise ValueError("Invalid value for `chromosome`, must not be `None`")  # noqa: E501

        self._chromosome = chromosome

    @property
    def number_of_probes(self):
        """Gets the number_of_probes of this CopyNumberSeg.  # noqa: E501


        :return: The number_of_probes of this CopyNumberSeg.  # noqa: E501
        :rtype: int
        """
        return self._number_of_probes

    @number_of_probes.setter
    def number_of_probes(self, number_of_probes):
        """Sets the number_of_probes of this CopyNumberSeg.


        :param number_of_probes: The number_of_probes of this CopyNumberSeg.  # noqa: E501
        :type: int
        """
        if number_of_probes is None:
            raise ValueError("Invalid value for `number_of_probes`, must not be `None`")  # noqa: E501

        self._number_of_probes = number_of_probes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CopyNumberSeg, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CopyNumberSeg):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
