# coding: utf-8

"""
    cBioPortal web Public API [Alpha]

    A web service for supplying JSON formatted data to cBioPortal clients. Please note that this API is currently in beta and subject to change.  # noqa: E501

    OpenAPI spec version: 1.0 (beta). Backwards compatibility will be maintained (after 1.0 release)
    Contact: cbioportal@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DiscreteCopyNumberData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'unique_sample_key': 'str',
        'unique_patient_key': 'str',
        'molecular_profile_id': 'str',
        'sample_id': 'str',
        'patient_id': 'str',
        'entrez_gene_id': 'int',
        'gene': 'Gene',
        'study_id': 'str',
        'driver_filter': 'str',
        'driver_filter_annotation': 'str',
        'driver_tiers_filter': 'str',
        'driver_tiers_filter_annotation': 'str',
        'alteration': 'int',
        'namespace_columns': 'object'
    }

    attribute_map = {
        'unique_sample_key': 'uniqueSampleKey',
        'unique_patient_key': 'uniquePatientKey',
        'molecular_profile_id': 'molecularProfileId',
        'sample_id': 'sampleId',
        'patient_id': 'patientId',
        'entrez_gene_id': 'entrezGeneId',
        'gene': 'gene',
        'study_id': 'studyId',
        'driver_filter': 'driverFilter',
        'driver_filter_annotation': 'driverFilterAnnotation',
        'driver_tiers_filter': 'driverTiersFilter',
        'driver_tiers_filter_annotation': 'driverTiersFilterAnnotation',
        'alteration': 'alteration',
        'namespace_columns': 'namespaceColumns'
    }

    def __init__(self, unique_sample_key=None, unique_patient_key=None, molecular_profile_id=None, sample_id=None, patient_id=None, entrez_gene_id=None, gene=None, study_id=None, driver_filter=None, driver_filter_annotation=None, driver_tiers_filter=None, driver_tiers_filter_annotation=None, alteration=None, namespace_columns=None):  # noqa: E501
        """DiscreteCopyNumberData - a model defined in Swagger"""  # noqa: E501
        self._unique_sample_key = None
        self._unique_patient_key = None
        self._molecular_profile_id = None
        self._sample_id = None
        self._patient_id = None
        self._entrez_gene_id = None
        self._gene = None
        self._study_id = None
        self._driver_filter = None
        self._driver_filter_annotation = None
        self._driver_tiers_filter = None
        self._driver_tiers_filter_annotation = None
        self._alteration = None
        self._namespace_columns = None
        self.discriminator = None
        if unique_sample_key is not None:
            self.unique_sample_key = unique_sample_key
        if unique_patient_key is not None:
            self.unique_patient_key = unique_patient_key
        self.molecular_profile_id = molecular_profile_id
        self.sample_id = sample_id
        self.patient_id = patient_id
        self.entrez_gene_id = entrez_gene_id
        if gene is not None:
            self.gene = gene
        self.study_id = study_id
        if driver_filter is not None:
            self.driver_filter = driver_filter
        if driver_filter_annotation is not None:
            self.driver_filter_annotation = driver_filter_annotation
        if driver_tiers_filter is not None:
            self.driver_tiers_filter = driver_tiers_filter
        if driver_tiers_filter_annotation is not None:
            self.driver_tiers_filter_annotation = driver_tiers_filter_annotation
        self.alteration = alteration
        if namespace_columns is not None:
            self.namespace_columns = namespace_columns

    @property
    def unique_sample_key(self):
        """Gets the unique_sample_key of this DiscreteCopyNumberData.  # noqa: E501


        :return: The unique_sample_key of this DiscreteCopyNumberData.  # noqa: E501
        :rtype: str
        """
        return self._unique_sample_key

    @unique_sample_key.setter
    def unique_sample_key(self, unique_sample_key):
        """Sets the unique_sample_key of this DiscreteCopyNumberData.


        :param unique_sample_key: The unique_sample_key of this DiscreteCopyNumberData.  # noqa: E501
        :type: str
        """

        self._unique_sample_key = unique_sample_key

    @property
    def unique_patient_key(self):
        """Gets the unique_patient_key of this DiscreteCopyNumberData.  # noqa: E501


        :return: The unique_patient_key of this DiscreteCopyNumberData.  # noqa: E501
        :rtype: str
        """
        return self._unique_patient_key

    @unique_patient_key.setter
    def unique_patient_key(self, unique_patient_key):
        """Sets the unique_patient_key of this DiscreteCopyNumberData.


        :param unique_patient_key: The unique_patient_key of this DiscreteCopyNumberData.  # noqa: E501
        :type: str
        """

        self._unique_patient_key = unique_patient_key

    @property
    def molecular_profile_id(self):
        """Gets the molecular_profile_id of this DiscreteCopyNumberData.  # noqa: E501


        :return: The molecular_profile_id of this DiscreteCopyNumberData.  # noqa: E501
        :rtype: str
        """
        return self._molecular_profile_id

    @molecular_profile_id.setter
    def molecular_profile_id(self, molecular_profile_id):
        """Sets the molecular_profile_id of this DiscreteCopyNumberData.


        :param molecular_profile_id: The molecular_profile_id of this DiscreteCopyNumberData.  # noqa: E501
        :type: str
        """
        if molecular_profile_id is None:
            raise ValueError("Invalid value for `molecular_profile_id`, must not be `None`")  # noqa: E501

        self._molecular_profile_id = molecular_profile_id

    @property
    def sample_id(self):
        """Gets the sample_id of this DiscreteCopyNumberData.  # noqa: E501


        :return: The sample_id of this DiscreteCopyNumberData.  # noqa: E501
        :rtype: str
        """
        return self._sample_id

    @sample_id.setter
    def sample_id(self, sample_id):
        """Sets the sample_id of this DiscreteCopyNumberData.


        :param sample_id: The sample_id of this DiscreteCopyNumberData.  # noqa: E501
        :type: str
        """
        if sample_id is None:
            raise ValueError("Invalid value for `sample_id`, must not be `None`")  # noqa: E501

        self._sample_id = sample_id

    @property
    def patient_id(self):
        """Gets the patient_id of this DiscreteCopyNumberData.  # noqa: E501


        :return: The patient_id of this DiscreteCopyNumberData.  # noqa: E501
        :rtype: str
        """
        return self._patient_id

    @patient_id.setter
    def patient_id(self, patient_id):
        """Sets the patient_id of this DiscreteCopyNumberData.


        :param patient_id: The patient_id of this DiscreteCopyNumberData.  # noqa: E501
        :type: str
        """
        if patient_id is None:
            raise ValueError("Invalid value for `patient_id`, must not be `None`")  # noqa: E501

        self._patient_id = patient_id

    @property
    def entrez_gene_id(self):
        """Gets the entrez_gene_id of this DiscreteCopyNumberData.  # noqa: E501


        :return: The entrez_gene_id of this DiscreteCopyNumberData.  # noqa: E501
        :rtype: int
        """
        return self._entrez_gene_id

    @entrez_gene_id.setter
    def entrez_gene_id(self, entrez_gene_id):
        """Sets the entrez_gene_id of this DiscreteCopyNumberData.


        :param entrez_gene_id: The entrez_gene_id of this DiscreteCopyNumberData.  # noqa: E501
        :type: int
        """
        if entrez_gene_id is None:
            raise ValueError("Invalid value for `entrez_gene_id`, must not be `None`")  # noqa: E501

        self._entrez_gene_id = entrez_gene_id

    @property
    def gene(self):
        """Gets the gene of this DiscreteCopyNumberData.  # noqa: E501


        :return: The gene of this DiscreteCopyNumberData.  # noqa: E501
        :rtype: Gene
        """
        return self._gene

    @gene.setter
    def gene(self, gene):
        """Sets the gene of this DiscreteCopyNumberData.


        :param gene: The gene of this DiscreteCopyNumberData.  # noqa: E501
        :type: Gene
        """

        self._gene = gene

    @property
    def study_id(self):
        """Gets the study_id of this DiscreteCopyNumberData.  # noqa: E501


        :return: The study_id of this DiscreteCopyNumberData.  # noqa: E501
        :rtype: str
        """
        return self._study_id

    @study_id.setter
    def study_id(self, study_id):
        """Sets the study_id of this DiscreteCopyNumberData.


        :param study_id: The study_id of this DiscreteCopyNumberData.  # noqa: E501
        :type: str
        """
        if study_id is None:
            raise ValueError("Invalid value for `study_id`, must not be `None`")  # noqa: E501

        self._study_id = study_id

    @property
    def driver_filter(self):
        """Gets the driver_filter of this DiscreteCopyNumberData.  # noqa: E501


        :return: The driver_filter of this DiscreteCopyNumberData.  # noqa: E501
        :rtype: str
        """
        return self._driver_filter

    @driver_filter.setter
    def driver_filter(self, driver_filter):
        """Sets the driver_filter of this DiscreteCopyNumberData.


        :param driver_filter: The driver_filter of this DiscreteCopyNumberData.  # noqa: E501
        :type: str
        """

        self._driver_filter = driver_filter

    @property
    def driver_filter_annotation(self):
        """Gets the driver_filter_annotation of this DiscreteCopyNumberData.  # noqa: E501


        :return: The driver_filter_annotation of this DiscreteCopyNumberData.  # noqa: E501
        :rtype: str
        """
        return self._driver_filter_annotation

    @driver_filter_annotation.setter
    def driver_filter_annotation(self, driver_filter_annotation):
        """Sets the driver_filter_annotation of this DiscreteCopyNumberData.


        :param driver_filter_annotation: The driver_filter_annotation of this DiscreteCopyNumberData.  # noqa: E501
        :type: str
        """

        self._driver_filter_annotation = driver_filter_annotation

    @property
    def driver_tiers_filter(self):
        """Gets the driver_tiers_filter of this DiscreteCopyNumberData.  # noqa: E501


        :return: The driver_tiers_filter of this DiscreteCopyNumberData.  # noqa: E501
        :rtype: str
        """
        return self._driver_tiers_filter

    @driver_tiers_filter.setter
    def driver_tiers_filter(self, driver_tiers_filter):
        """Sets the driver_tiers_filter of this DiscreteCopyNumberData.


        :param driver_tiers_filter: The driver_tiers_filter of this DiscreteCopyNumberData.  # noqa: E501
        :type: str
        """

        self._driver_tiers_filter = driver_tiers_filter

    @property
    def driver_tiers_filter_annotation(self):
        """Gets the driver_tiers_filter_annotation of this DiscreteCopyNumberData.  # noqa: E501


        :return: The driver_tiers_filter_annotation of this DiscreteCopyNumberData.  # noqa: E501
        :rtype: str
        """
        return self._driver_tiers_filter_annotation

    @driver_tiers_filter_annotation.setter
    def driver_tiers_filter_annotation(self, driver_tiers_filter_annotation):
        """Sets the driver_tiers_filter_annotation of this DiscreteCopyNumberData.


        :param driver_tiers_filter_annotation: The driver_tiers_filter_annotation of this DiscreteCopyNumberData.  # noqa: E501
        :type: str
        """

        self._driver_tiers_filter_annotation = driver_tiers_filter_annotation

    @property
    def alteration(self):
        """Gets the alteration of this DiscreteCopyNumberData.  # noqa: E501


        :return: The alteration of this DiscreteCopyNumberData.  # noqa: E501
        :rtype: int
        """
        return self._alteration

    @alteration.setter
    def alteration(self, alteration):
        """Sets the alteration of this DiscreteCopyNumberData.


        :param alteration: The alteration of this DiscreteCopyNumberData.  # noqa: E501
        :type: int
        """
        if alteration is None:
            raise ValueError("Invalid value for `alteration`, must not be `None`")  # noqa: E501

        self._alteration = alteration

    @property
    def namespace_columns(self):
        """Gets the namespace_columns of this DiscreteCopyNumberData.  # noqa: E501


        :return: The namespace_columns of this DiscreteCopyNumberData.  # noqa: E501
        :rtype: object
        """
        return self._namespace_columns

    @namespace_columns.setter
    def namespace_columns(self, namespace_columns):
        """Sets the namespace_columns of this DiscreteCopyNumberData.


        :param namespace_columns: The namespace_columns of this DiscreteCopyNumberData.  # noqa: E501
        :type: object
        """

        self._namespace_columns = namespace_columns

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DiscreteCopyNumberData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DiscreteCopyNumberData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
