# coding: utf-8

"""
    cBioPortal web Public API [Alpha]

    A web service for supplying JSON formatted data to cBioPortal clients. Please note that this API is currently in beta and subject to change.  # noqa: E501

    OpenAPI spec version: 1.0 (beta). Backwards compatibility will be maintained (after 1.0 release)
    Contact: cbioportal@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Gene(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'genetic_entity_id': 'int',
        'entrez_gene_id': 'int',
        'hugo_gene_symbol': 'str',
        'type': 'str'
    }

    attribute_map = {
        'genetic_entity_id': 'geneticEntityId',
        'entrez_gene_id': 'entrezGeneId',
        'hugo_gene_symbol': 'hugoGeneSymbol',
        'type': 'type'
    }

    def __init__(self, genetic_entity_id=None, entrez_gene_id=None, hugo_gene_symbol=None, type=None):  # noqa: E501
        """Gene - a model defined in Swagger"""  # noqa: E501
        self._genetic_entity_id = None
        self._entrez_gene_id = None
        self._hugo_gene_symbol = None
        self._type = None
        self.discriminator = None
        self.genetic_entity_id = genetic_entity_id
        self.entrez_gene_id = entrez_gene_id
        self.hugo_gene_symbol = hugo_gene_symbol
        if type is not None:
            self.type = type

    @property
    def genetic_entity_id(self):
        """Gets the genetic_entity_id of this Gene.  # noqa: E501


        :return: The genetic_entity_id of this Gene.  # noqa: E501
        :rtype: int
        """
        return self._genetic_entity_id

    @genetic_entity_id.setter
    def genetic_entity_id(self, genetic_entity_id):
        """Sets the genetic_entity_id of this Gene.


        :param genetic_entity_id: The genetic_entity_id of this Gene.  # noqa: E501
        :type: int
        """
        if genetic_entity_id is None:
            raise ValueError("Invalid value for `genetic_entity_id`, must not be `None`")  # noqa: E501

        self._genetic_entity_id = genetic_entity_id

    @property
    def entrez_gene_id(self):
        """Gets the entrez_gene_id of this Gene.  # noqa: E501


        :return: The entrez_gene_id of this Gene.  # noqa: E501
        :rtype: int
        """
        return self._entrez_gene_id

    @entrez_gene_id.setter
    def entrez_gene_id(self, entrez_gene_id):
        """Sets the entrez_gene_id of this Gene.


        :param entrez_gene_id: The entrez_gene_id of this Gene.  # noqa: E501
        :type: int
        """
        if entrez_gene_id is None:
            raise ValueError("Invalid value for `entrez_gene_id`, must not be `None`")  # noqa: E501

        self._entrez_gene_id = entrez_gene_id

    @property
    def hugo_gene_symbol(self):
        """Gets the hugo_gene_symbol of this Gene.  # noqa: E501


        :return: The hugo_gene_symbol of this Gene.  # noqa: E501
        :rtype: str
        """
        return self._hugo_gene_symbol

    @hugo_gene_symbol.setter
    def hugo_gene_symbol(self, hugo_gene_symbol):
        """Sets the hugo_gene_symbol of this Gene.


        :param hugo_gene_symbol: The hugo_gene_symbol of this Gene.  # noqa: E501
        :type: str
        """
        if hugo_gene_symbol is None:
            raise ValueError("Invalid value for `hugo_gene_symbol`, must not be `None`")  # noqa: E501

        self._hugo_gene_symbol = hugo_gene_symbol

    @property
    def type(self):
        """Gets the type of this Gene.  # noqa: E501


        :return: The type of this Gene.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Gene.


        :param type: The type of this Gene.  # noqa: E501
        :type: str
        """

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Gene, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Gene):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
