# coding: utf-8

"""
    cBioPortal web Public API [Alpha]

    A web service for supplying JSON formatted data to cBioPortal clients. Please note that this API is currently in beta and subject to change.  # noqa: E501

    OpenAPI spec version: 1.0 (beta). Backwards compatibility will be maintained (after 1.0 release)
    Contact: cbioportal@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GenericAssayMetaFilter(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'molecular_profile_ids': 'list[str]',
        'generic_assay_stable_ids': 'list[str]'
    }

    attribute_map = {
        'molecular_profile_ids': 'molecularProfileIds',
        'generic_assay_stable_ids': 'genericAssayStableIds'
    }

    def __init__(self, molecular_profile_ids=None, generic_assay_stable_ids=None):  # noqa: E501
        """GenericAssayMetaFilter - a model defined in Swagger"""  # noqa: E501
        self._molecular_profile_ids = None
        self._generic_assay_stable_ids = None
        self.discriminator = None
        if molecular_profile_ids is not None:
            self.molecular_profile_ids = molecular_profile_ids
        if generic_assay_stable_ids is not None:
            self.generic_assay_stable_ids = generic_assay_stable_ids

    @property
    def molecular_profile_ids(self):
        """Gets the molecular_profile_ids of this GenericAssayMetaFilter.  # noqa: E501


        :return: The molecular_profile_ids of this GenericAssayMetaFilter.  # noqa: E501
        :rtype: list[str]
        """
        return self._molecular_profile_ids

    @molecular_profile_ids.setter
    def molecular_profile_ids(self, molecular_profile_ids):
        """Sets the molecular_profile_ids of this GenericAssayMetaFilter.


        :param molecular_profile_ids: The molecular_profile_ids of this GenericAssayMetaFilter.  # noqa: E501
        :type: list[str]
        """

        self._molecular_profile_ids = molecular_profile_ids

    @property
    def generic_assay_stable_ids(self):
        """Gets the generic_assay_stable_ids of this GenericAssayMetaFilter.  # noqa: E501


        :return: The generic_assay_stable_ids of this GenericAssayMetaFilter.  # noqa: E501
        :rtype: list[str]
        """
        return self._generic_assay_stable_ids

    @generic_assay_stable_ids.setter
    def generic_assay_stable_ids(self, generic_assay_stable_ids):
        """Sets the generic_assay_stable_ids of this GenericAssayMetaFilter.


        :param generic_assay_stable_ids: The generic_assay_stable_ids of this GenericAssayMetaFilter.  # noqa: E501
        :type: list[str]
        """

        self._generic_assay_stable_ids = generic_assay_stable_ids

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GenericAssayMetaFilter, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GenericAssayMetaFilter):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
