# coding: utf-8

"""
    cBioPortal web Public API [Alpha]

    A web service for supplying JSON formatted data to cBioPortal clients. Please note that this API is currently in beta and subject to change.  # noqa: E501

    OpenAPI spec version: 1.0 (beta). Backwards compatibility will be maintained (after 1.0 release)
    Contact: cbioportal@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GenePanel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'description': 'str',
        'genes': 'list[GenePanelToGene]',
        'gene_panel_id': 'str'
    }

    attribute_map = {
        'description': 'description',
        'genes': 'genes',
        'gene_panel_id': 'genePanelId'
    }

    def __init__(self, description=None, genes=None, gene_panel_id=None):  # noqa: E501
        """GenePanel - a model defined in Swagger"""  # noqa: E501
        self._description = None
        self._genes = None
        self._gene_panel_id = None
        self.discriminator = None
        if description is not None:
            self.description = description
        if genes is not None:
            self.genes = genes
        self.gene_panel_id = gene_panel_id

    @property
    def description(self):
        """Gets the description of this GenePanel.  # noqa: E501


        :return: The description of this GenePanel.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this GenePanel.


        :param description: The description of this GenePanel.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def genes(self):
        """Gets the genes of this GenePanel.  # noqa: E501


        :return: The genes of this GenePanel.  # noqa: E501
        :rtype: list[GenePanelToGene]
        """
        return self._genes

    @genes.setter
    def genes(self, genes):
        """Sets the genes of this GenePanel.


        :param genes: The genes of this GenePanel.  # noqa: E501
        :type: list[GenePanelToGene]
        """

        self._genes = genes

    @property
    def gene_panel_id(self):
        """Gets the gene_panel_id of this GenePanel.  # noqa: E501


        :return: The gene_panel_id of this GenePanel.  # noqa: E501
        :rtype: str
        """
        return self._gene_panel_id

    @gene_panel_id.setter
    def gene_panel_id(self, gene_panel_id):
        """Sets the gene_panel_id of this GenePanel.


        :param gene_panel_id: The gene_panel_id of this GenePanel.  # noqa: E501
        :type: str
        """
        if gene_panel_id is None:
            raise ValueError("Invalid value for `gene_panel_id`, must not be `None`")  # noqa: E501

        self._gene_panel_id = gene_panel_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GenePanel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GenePanel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
