# coding: utf-8

"""
    cBioPortal web Public API [Alpha]

    A web service for supplying JSON formatted data to cBioPortal clients. Please note that this API is currently in beta and subject to change.  # noqa: E501

    OpenAPI spec version: 1.0 (beta). Backwards compatibility will be maintained (after 1.0 release)
    Contact: cbioportal@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GenericAssayMeta(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'stable_id': 'str',
        'entity_type': 'str',
        'generic_entity_meta_properties': 'dict(str, str)'
    }

    attribute_map = {
        'stable_id': 'stableId',
        'entity_type': 'entityType',
        'generic_entity_meta_properties': 'genericEntityMetaProperties'
    }

    def __init__(self, stable_id=None, entity_type=None, generic_entity_meta_properties=None):  # noqa: E501
        """GenericAssayMeta - a model defined in Swagger"""  # noqa: E501
        self._stable_id = None
        self._entity_type = None
        self._generic_entity_meta_properties = None
        self.discriminator = None
        if stable_id is not None:
            self.stable_id = stable_id
        if entity_type is not None:
            self.entity_type = entity_type
        if generic_entity_meta_properties is not None:
            self.generic_entity_meta_properties = generic_entity_meta_properties

    @property
    def stable_id(self):
        """Gets the stable_id of this GenericAssayMeta.  # noqa: E501


        :return: The stable_id of this GenericAssayMeta.  # noqa: E501
        :rtype: str
        """
        return self._stable_id

    @stable_id.setter
    def stable_id(self, stable_id):
        """Sets the stable_id of this GenericAssayMeta.


        :param stable_id: The stable_id of this GenericAssayMeta.  # noqa: E501
        :type: str
        """

        self._stable_id = stable_id

    @property
    def entity_type(self):
        """Gets the entity_type of this GenericAssayMeta.  # noqa: E501


        :return: The entity_type of this GenericAssayMeta.  # noqa: E501
        :rtype: str
        """
        return self._entity_type

    @entity_type.setter
    def entity_type(self, entity_type):
        """Sets the entity_type of this GenericAssayMeta.


        :param entity_type: The entity_type of this GenericAssayMeta.  # noqa: E501
        :type: str
        """

        self._entity_type = entity_type

    @property
    def generic_entity_meta_properties(self):
        """Gets the generic_entity_meta_properties of this GenericAssayMeta.  # noqa: E501


        :return: The generic_entity_meta_properties of this GenericAssayMeta.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._generic_entity_meta_properties

    @generic_entity_meta_properties.setter
    def generic_entity_meta_properties(self, generic_entity_meta_properties):
        """Sets the generic_entity_meta_properties of this GenericAssayMeta.


        :param generic_entity_meta_properties: The generic_entity_meta_properties of this GenericAssayMeta.  # noqa: E501
        :type: dict(str, str)
        """

        self._generic_entity_meta_properties = generic_entity_meta_properties

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GenericAssayMeta, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GenericAssayMeta):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
