# coding: utf-8

"""
    cBioPortal web Public API [Alpha]

    A web service for supplying JSON formatted data to cBioPortal clients. Please note that this API is currently in beta and subject to change.  # noqa: E501

    OpenAPI spec version: 1.0 (beta). Backwards compatibility will be maintained (after 1.0 release)
    Contact: cbioportal@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GenePanelDataFilter(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'sample_ids': 'list[str]',
        'sample_list_id': 'str'
    }

    attribute_map = {
        'sample_ids': 'sampleIds',
        'sample_list_id': 'sampleListId'
    }

    def __init__(self, sample_ids=None, sample_list_id=None):  # noqa: E501
        """GenePanelDataFilter - a model defined in Swagger"""  # noqa: E501
        self._sample_ids = None
        self._sample_list_id = None
        self.discriminator = None
        if sample_ids is not None:
            self.sample_ids = sample_ids
        if sample_list_id is not None:
            self.sample_list_id = sample_list_id

    @property
    def sample_ids(self):
        """Gets the sample_ids of this GenePanelDataFilter.  # noqa: E501


        :return: The sample_ids of this GenePanelDataFilter.  # noqa: E501
        :rtype: list[str]
        """
        return self._sample_ids

    @sample_ids.setter
    def sample_ids(self, sample_ids):
        """Sets the sample_ids of this GenePanelDataFilter.


        :param sample_ids: The sample_ids of this GenePanelDataFilter.  # noqa: E501
        :type: list[str]
        """

        self._sample_ids = sample_ids

    @property
    def sample_list_id(self):
        """Gets the sample_list_id of this GenePanelDataFilter.  # noqa: E501


        :return: The sample_list_id of this GenePanelDataFilter.  # noqa: E501
        :rtype: str
        """
        return self._sample_list_id

    @sample_list_id.setter
    def sample_list_id(self, sample_list_id):
        """Sets the sample_list_id of this GenePanelDataFilter.


        :param sample_list_id: The sample_list_id of this GenePanelDataFilter.  # noqa: E501
        :type: str
        """

        self._sample_list_id = sample_list_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GenePanelDataFilter, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GenePanelDataFilter):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
