# coding: utf-8

"""
    cBioPortal web Public API [Alpha]

    A web service for supplying JSON formatted data to cBioPortal clients. Please note that this API is currently in beta and subject to change.  # noqa: E501

    OpenAPI spec version: 1.0 (beta). Backwards compatibility will be maintained (after 1.0 release)
    Contact: cbioportal@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Info(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'portal_version': 'str',
        'db_version': 'str',
        'derived_table_version': 'str',
        'geneset_version': 'str',
        'gene_table_version': 'str',
        'git_branch': 'str',
        'git_commit_id': 'str',
        'git_commit_id_abbrev': 'str',
        'git_commit_id_describe': 'str',
        'git_commit_id_describe_short': 'str',
        'git_commit_message_full': 'str',
        'git_commit_message_short': 'str',
        'git_commit_message_user_email': 'str',
        'git_commit_message_user_name': 'str',
        'git_dirty': 'bool'
    }

    attribute_map = {
        'portal_version': 'portalVersion',
        'db_version': 'dbVersion',
        'derived_table_version': 'derivedTableVersion',
        'geneset_version': 'genesetVersion',
        'gene_table_version': 'geneTableVersion',
        'git_branch': 'gitBranch',
        'git_commit_id': 'gitCommitId',
        'git_commit_id_abbrev': 'gitCommitIdAbbrev',
        'git_commit_id_describe': 'gitCommitIdDescribe',
        'git_commit_id_describe_short': 'gitCommitIdDescribeShort',
        'git_commit_message_full': 'gitCommitMessageFull',
        'git_commit_message_short': 'gitCommitMessageShort',
        'git_commit_message_user_email': 'gitCommitMessageUserEmail',
        'git_commit_message_user_name': 'gitCommitMessageUserName',
        'git_dirty': 'gitDirty'
    }

    def __init__(self, portal_version=None, db_version=None, derived_table_version=None, geneset_version=None, gene_table_version=None, git_branch=None, git_commit_id=None, git_commit_id_abbrev=None, git_commit_id_describe=None, git_commit_id_describe_short=None, git_commit_message_full=None, git_commit_message_short=None, git_commit_message_user_email=None, git_commit_message_user_name=None, git_dirty=None):  # noqa: E501
        """Info - a model defined in Swagger"""  # noqa: E501
        self._portal_version = None
        self._db_version = None
        self._derived_table_version = None
        self._geneset_version = None
        self._gene_table_version = None
        self._git_branch = None
        self._git_commit_id = None
        self._git_commit_id_abbrev = None
        self._git_commit_id_describe = None
        self._git_commit_id_describe_short = None
        self._git_commit_message_full = None
        self._git_commit_message_short = None
        self._git_commit_message_user_email = None
        self._git_commit_message_user_name = None
        self._git_dirty = None
        self.discriminator = None
        self.portal_version = portal_version
        self.db_version = db_version
        self.derived_table_version = derived_table_version
        self.geneset_version = geneset_version
        self.gene_table_version = gene_table_version
        self.git_branch = git_branch
        self.git_commit_id = git_commit_id
        self.git_commit_id_abbrev = git_commit_id_abbrev
        self.git_commit_id_describe = git_commit_id_describe
        self.git_commit_id_describe_short = git_commit_id_describe_short
        self.git_commit_message_full = git_commit_message_full
        self.git_commit_message_short = git_commit_message_short
        self.git_commit_message_user_email = git_commit_message_user_email
        self.git_commit_message_user_name = git_commit_message_user_name
        self.git_dirty = git_dirty

    @property
    def portal_version(self):
        """Gets the portal_version of this Info.  # noqa: E501


        :return: The portal_version of this Info.  # noqa: E501
        :rtype: str
        """
        return self._portal_version

    @portal_version.setter
    def portal_version(self, portal_version):
        """Sets the portal_version of this Info.


        :param portal_version: The portal_version of this Info.  # noqa: E501
        :type: str
        """
        if portal_version is None:
            raise ValueError("Invalid value for `portal_version`, must not be `None`")  # noqa: E501

        self._portal_version = portal_version

    @property
    def db_version(self):
        """Gets the db_version of this Info.  # noqa: E501


        :return: The db_version of this Info.  # noqa: E501
        :rtype: str
        """
        return self._db_version

    @db_version.setter
    def db_version(self, db_version):
        """Sets the db_version of this Info.


        :param db_version: The db_version of this Info.  # noqa: E501
        :type: str
        """
        if db_version is None:
            raise ValueError("Invalid value for `db_version`, must not be `None`")  # noqa: E501

        self._db_version = db_version

    @property
    def derived_table_version(self):
        """Gets the derived_table_version of this Info.  # noqa: E501


        :return: The derived_table_version of this Info.  # noqa: E501
        :rtype: str
        """
        return self._derived_table_version

    @derived_table_version.setter
    def derived_table_version(self, derived_table_version):
        """Sets the derived_table_version of this Info.


        :param derived_table_version: The derived_table_version of this Info.  # noqa: E501
        :type: str
        """
        if derived_table_version is None:
            raise ValueError("Invalid value for `derived_table_version`, must not be `None`")  # noqa: E501

        self._derived_table_version = derived_table_version

    @property
    def geneset_version(self):
        """Gets the geneset_version of this Info.  # noqa: E501


        :return: The geneset_version of this Info.  # noqa: E501
        :rtype: str
        """
        return self._geneset_version

    @geneset_version.setter
    def geneset_version(self, geneset_version):
        """Sets the geneset_version of this Info.


        :param geneset_version: The geneset_version of this Info.  # noqa: E501
        :type: str
        """
        if geneset_version is None:
            raise ValueError("Invalid value for `geneset_version`, must not be `None`")  # noqa: E501

        self._geneset_version = geneset_version

    @property
    def gene_table_version(self):
        """Gets the gene_table_version of this Info.  # noqa: E501


        :return: The gene_table_version of this Info.  # noqa: E501
        :rtype: str
        """
        return self._gene_table_version

    @gene_table_version.setter
    def gene_table_version(self, gene_table_version):
        """Sets the gene_table_version of this Info.


        :param gene_table_version: The gene_table_version of this Info.  # noqa: E501
        :type: str
        """
        if gene_table_version is None:
            raise ValueError("Invalid value for `gene_table_version`, must not be `None`")  # noqa: E501

        self._gene_table_version = gene_table_version

    @property
    def git_branch(self):
        """Gets the git_branch of this Info.  # noqa: E501


        :return: The git_branch of this Info.  # noqa: E501
        :rtype: str
        """
        return self._git_branch

    @git_branch.setter
    def git_branch(self, git_branch):
        """Sets the git_branch of this Info.


        :param git_branch: The git_branch of this Info.  # noqa: E501
        :type: str
        """
        if git_branch is None:
            raise ValueError("Invalid value for `git_branch`, must not be `None`")  # noqa: E501

        self._git_branch = git_branch

    @property
    def git_commit_id(self):
        """Gets the git_commit_id of this Info.  # noqa: E501


        :return: The git_commit_id of this Info.  # noqa: E501
        :rtype: str
        """
        return self._git_commit_id

    @git_commit_id.setter
    def git_commit_id(self, git_commit_id):
        """Sets the git_commit_id of this Info.


        :param git_commit_id: The git_commit_id of this Info.  # noqa: E501
        :type: str
        """
        if git_commit_id is None:
            raise ValueError("Invalid value for `git_commit_id`, must not be `None`")  # noqa: E501

        self._git_commit_id = git_commit_id

    @property
    def git_commit_id_abbrev(self):
        """Gets the git_commit_id_abbrev of this Info.  # noqa: E501


        :return: The git_commit_id_abbrev of this Info.  # noqa: E501
        :rtype: str
        """
        return self._git_commit_id_abbrev

    @git_commit_id_abbrev.setter
    def git_commit_id_abbrev(self, git_commit_id_abbrev):
        """Sets the git_commit_id_abbrev of this Info.


        :param git_commit_id_abbrev: The git_commit_id_abbrev of this Info.  # noqa: E501
        :type: str
        """
        if git_commit_id_abbrev is None:
            raise ValueError("Invalid value for `git_commit_id_abbrev`, must not be `None`")  # noqa: E501

        self._git_commit_id_abbrev = git_commit_id_abbrev

    @property
    def git_commit_id_describe(self):
        """Gets the git_commit_id_describe of this Info.  # noqa: E501


        :return: The git_commit_id_describe of this Info.  # noqa: E501
        :rtype: str
        """
        return self._git_commit_id_describe

    @git_commit_id_describe.setter
    def git_commit_id_describe(self, git_commit_id_describe):
        """Sets the git_commit_id_describe of this Info.


        :param git_commit_id_describe: The git_commit_id_describe of this Info.  # noqa: E501
        :type: str
        """
        if git_commit_id_describe is None:
            raise ValueError("Invalid value for `git_commit_id_describe`, must not be `None`")  # noqa: E501

        self._git_commit_id_describe = git_commit_id_describe

    @property
    def git_commit_id_describe_short(self):
        """Gets the git_commit_id_describe_short of this Info.  # noqa: E501


        :return: The git_commit_id_describe_short of this Info.  # noqa: E501
        :rtype: str
        """
        return self._git_commit_id_describe_short

    @git_commit_id_describe_short.setter
    def git_commit_id_describe_short(self, git_commit_id_describe_short):
        """Sets the git_commit_id_describe_short of this Info.


        :param git_commit_id_describe_short: The git_commit_id_describe_short of this Info.  # noqa: E501
        :type: str
        """
        if git_commit_id_describe_short is None:
            raise ValueError("Invalid value for `git_commit_id_describe_short`, must not be `None`")  # noqa: E501

        self._git_commit_id_describe_short = git_commit_id_describe_short

    @property
    def git_commit_message_full(self):
        """Gets the git_commit_message_full of this Info.  # noqa: E501


        :return: The git_commit_message_full of this Info.  # noqa: E501
        :rtype: str
        """
        return self._git_commit_message_full

    @git_commit_message_full.setter
    def git_commit_message_full(self, git_commit_message_full):
        """Sets the git_commit_message_full of this Info.


        :param git_commit_message_full: The git_commit_message_full of this Info.  # noqa: E501
        :type: str
        """
        if git_commit_message_full is None:
            raise ValueError("Invalid value for `git_commit_message_full`, must not be `None`")  # noqa: E501

        self._git_commit_message_full = git_commit_message_full

    @property
    def git_commit_message_short(self):
        """Gets the git_commit_message_short of this Info.  # noqa: E501


        :return: The git_commit_message_short of this Info.  # noqa: E501
        :rtype: str
        """
        return self._git_commit_message_short

    @git_commit_message_short.setter
    def git_commit_message_short(self, git_commit_message_short):
        """Sets the git_commit_message_short of this Info.


        :param git_commit_message_short: The git_commit_message_short of this Info.  # noqa: E501
        :type: str
        """
        if git_commit_message_short is None:
            raise ValueError("Invalid value for `git_commit_message_short`, must not be `None`")  # noqa: E501

        self._git_commit_message_short = git_commit_message_short

    @property
    def git_commit_message_user_email(self):
        """Gets the git_commit_message_user_email of this Info.  # noqa: E501


        :return: The git_commit_message_user_email of this Info.  # noqa: E501
        :rtype: str
        """
        return self._git_commit_message_user_email

    @git_commit_message_user_email.setter
    def git_commit_message_user_email(self, git_commit_message_user_email):
        """Sets the git_commit_message_user_email of this Info.


        :param git_commit_message_user_email: The git_commit_message_user_email of this Info.  # noqa: E501
        :type: str
        """
        if git_commit_message_user_email is None:
            raise ValueError("Invalid value for `git_commit_message_user_email`, must not be `None`")  # noqa: E501

        self._git_commit_message_user_email = git_commit_message_user_email

    @property
    def git_commit_message_user_name(self):
        """Gets the git_commit_message_user_name of this Info.  # noqa: E501


        :return: The git_commit_message_user_name of this Info.  # noqa: E501
        :rtype: str
        """
        return self._git_commit_message_user_name

    @git_commit_message_user_name.setter
    def git_commit_message_user_name(self, git_commit_message_user_name):
        """Sets the git_commit_message_user_name of this Info.


        :param git_commit_message_user_name: The git_commit_message_user_name of this Info.  # noqa: E501
        :type: str
        """
        if git_commit_message_user_name is None:
            raise ValueError("Invalid value for `git_commit_message_user_name`, must not be `None`")  # noqa: E501

        self._git_commit_message_user_name = git_commit_message_user_name

    @property
    def git_dirty(self):
        """Gets the git_dirty of this Info.  # noqa: E501


        :return: The git_dirty of this Info.  # noqa: E501
        :rtype: bool
        """
        return self._git_dirty

    @git_dirty.setter
    def git_dirty(self, git_dirty):
        """Sets the git_dirty of this Info.


        :param git_dirty: The git_dirty of this Info.  # noqa: E501
        :type: bool
        """
        if git_dirty is None:
            raise ValueError("Invalid value for `git_dirty`, must not be `None`")  # noqa: E501

        self._git_dirty = git_dirty

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Info, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Info):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
