# coding: utf-8

"""
    cBioPortal web Public API [Alpha]

    A web service for supplying JSON formatted data to cBioPortal clients. Please note that this API is currently in beta and subject to change.  # noqa: E501

    OpenAPI spec version: 1.0 (beta). Backwards compatibility will be maintained (after 1.0 release)
    Contact: cbioportal@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MolecularProfile(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'molecular_alteration_type': 'str',
        'generic_assay_type': 'str',
        'datatype': 'str',
        'name': 'str',
        'description': 'str',
        'show_profile_in_analysis_tab': 'bool',
        'pivot_threshold': 'float',
        'sort_order': 'str',
        'patient_level': 'bool',
        'molecular_profile_id': 'str',
        'study_id': 'str',
        'study': 'CancerStudy'
    }

    attribute_map = {
        'molecular_alteration_type': 'molecularAlterationType',
        'generic_assay_type': 'genericAssayType',
        'datatype': 'datatype',
        'name': 'name',
        'description': 'description',
        'show_profile_in_analysis_tab': 'showProfileInAnalysisTab',
        'pivot_threshold': 'pivotThreshold',
        'sort_order': 'sortOrder',
        'patient_level': 'patientLevel',
        'molecular_profile_id': 'molecularProfileId',
        'study_id': 'studyId',
        'study': 'study'
    }

    def __init__(self, molecular_alteration_type=None, generic_assay_type=None, datatype=None, name=None, description=None, show_profile_in_analysis_tab=None, pivot_threshold=None, sort_order=None, patient_level=None, molecular_profile_id=None, study_id=None, study=None):  # noqa: E501
        """MolecularProfile - a model defined in Swagger"""  # noqa: E501
        self._molecular_alteration_type = None
        self._generic_assay_type = None
        self._datatype = None
        self._name = None
        self._description = None
        self._show_profile_in_analysis_tab = None
        self._pivot_threshold = None
        self._sort_order = None
        self._patient_level = None
        self._molecular_profile_id = None
        self._study_id = None
        self._study = None
        self.discriminator = None
        if molecular_alteration_type is not None:
            self.molecular_alteration_type = molecular_alteration_type
        if generic_assay_type is not None:
            self.generic_assay_type = generic_assay_type
        if datatype is not None:
            self.datatype = datatype
        if name is not None:
            self.name = name
        if description is not None:
            self.description = description
        if show_profile_in_analysis_tab is not None:
            self.show_profile_in_analysis_tab = show_profile_in_analysis_tab
        if pivot_threshold is not None:
            self.pivot_threshold = pivot_threshold
        if sort_order is not None:
            self.sort_order = sort_order
        self.patient_level = patient_level
        self.molecular_profile_id = molecular_profile_id
        self.study_id = study_id
        if study is not None:
            self.study = study

    @property
    def molecular_alteration_type(self):
        """Gets the molecular_alteration_type of this MolecularProfile.  # noqa: E501


        :return: The molecular_alteration_type of this MolecularProfile.  # noqa: E501
        :rtype: str
        """
        return self._molecular_alteration_type

    @molecular_alteration_type.setter
    def molecular_alteration_type(self, molecular_alteration_type):
        """Sets the molecular_alteration_type of this MolecularProfile.


        :param molecular_alteration_type: The molecular_alteration_type of this MolecularProfile.  # noqa: E501
        :type: str
        """
        allowed_values = ["MUTATION_EXTENDED", "MUTATION_UNCALLED", "STRUCTURAL_VARIANT", "COPY_NUMBER_ALTERATION", "MICRO_RNA_EXPRESSION", "MRNA_EXPRESSION", "MRNA_EXPRESSION_NORMALS", "RNA_EXPRESSION", "METHYLATION", "METHYLATION_BINARY", "PHOSPHORYLATION", "PROTEIN_LEVEL", "PROTEIN_ARRAY_PROTEIN_LEVEL", "PROTEIN_ARRAY_PHOSPHORYLATION", "GENESET_SCORE", "GENERIC_ASSAY"]  # noqa: E501
        if molecular_alteration_type not in allowed_values:
            raise ValueError(
                "Invalid value for `molecular_alteration_type` ({0}), must be one of {1}"  # noqa: E501
                .format(molecular_alteration_type, allowed_values)
            )

        self._molecular_alteration_type = molecular_alteration_type

    @property
    def generic_assay_type(self):
        """Gets the generic_assay_type of this MolecularProfile.  # noqa: E501


        :return: The generic_assay_type of this MolecularProfile.  # noqa: E501
        :rtype: str
        """
        return self._generic_assay_type

    @generic_assay_type.setter
    def generic_assay_type(self, generic_assay_type):
        """Sets the generic_assay_type of this MolecularProfile.


        :param generic_assay_type: The generic_assay_type of this MolecularProfile.  # noqa: E501
        :type: str
        """

        self._generic_assay_type = generic_assay_type

    @property
    def datatype(self):
        """Gets the datatype of this MolecularProfile.  # noqa: E501


        :return: The datatype of this MolecularProfile.  # noqa: E501
        :rtype: str
        """
        return self._datatype

    @datatype.setter
    def datatype(self, datatype):
        """Sets the datatype of this MolecularProfile.


        :param datatype: The datatype of this MolecularProfile.  # noqa: E501
        :type: str
        """

        self._datatype = datatype

    @property
    def name(self):
        """Gets the name of this MolecularProfile.  # noqa: E501


        :return: The name of this MolecularProfile.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this MolecularProfile.


        :param name: The name of this MolecularProfile.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """Gets the description of this MolecularProfile.  # noqa: E501


        :return: The description of this MolecularProfile.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this MolecularProfile.


        :param description: The description of this MolecularProfile.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def show_profile_in_analysis_tab(self):
        """Gets the show_profile_in_analysis_tab of this MolecularProfile.  # noqa: E501


        :return: The show_profile_in_analysis_tab of this MolecularProfile.  # noqa: E501
        :rtype: bool
        """
        return self._show_profile_in_analysis_tab

    @show_profile_in_analysis_tab.setter
    def show_profile_in_analysis_tab(self, show_profile_in_analysis_tab):
        """Sets the show_profile_in_analysis_tab of this MolecularProfile.


        :param show_profile_in_analysis_tab: The show_profile_in_analysis_tab of this MolecularProfile.  # noqa: E501
        :type: bool
        """

        self._show_profile_in_analysis_tab = show_profile_in_analysis_tab

    @property
    def pivot_threshold(self):
        """Gets the pivot_threshold of this MolecularProfile.  # noqa: E501


        :return: The pivot_threshold of this MolecularProfile.  # noqa: E501
        :rtype: float
        """
        return self._pivot_threshold

    @pivot_threshold.setter
    def pivot_threshold(self, pivot_threshold):
        """Sets the pivot_threshold of this MolecularProfile.


        :param pivot_threshold: The pivot_threshold of this MolecularProfile.  # noqa: E501
        :type: float
        """

        self._pivot_threshold = pivot_threshold

    @property
    def sort_order(self):
        """Gets the sort_order of this MolecularProfile.  # noqa: E501


        :return: The sort_order of this MolecularProfile.  # noqa: E501
        :rtype: str
        """
        return self._sort_order

    @sort_order.setter
    def sort_order(self, sort_order):
        """Sets the sort_order of this MolecularProfile.


        :param sort_order: The sort_order of this MolecularProfile.  # noqa: E501
        :type: str
        """

        self._sort_order = sort_order

    @property
    def patient_level(self):
        """Gets the patient_level of this MolecularProfile.  # noqa: E501


        :return: The patient_level of this MolecularProfile.  # noqa: E501
        :rtype: bool
        """
        return self._patient_level

    @patient_level.setter
    def patient_level(self, patient_level):
        """Sets the patient_level of this MolecularProfile.


        :param patient_level: The patient_level of this MolecularProfile.  # noqa: E501
        :type: bool
        """
        if patient_level is None:
            raise ValueError("Invalid value for `patient_level`, must not be `None`")  # noqa: E501

        self._patient_level = patient_level

    @property
    def molecular_profile_id(self):
        """Gets the molecular_profile_id of this MolecularProfile.  # noqa: E501


        :return: The molecular_profile_id of this MolecularProfile.  # noqa: E501
        :rtype: str
        """
        return self._molecular_profile_id

    @molecular_profile_id.setter
    def molecular_profile_id(self, molecular_profile_id):
        """Sets the molecular_profile_id of this MolecularProfile.


        :param molecular_profile_id: The molecular_profile_id of this MolecularProfile.  # noqa: E501
        :type: str
        """
        if molecular_profile_id is None:
            raise ValueError("Invalid value for `molecular_profile_id`, must not be `None`")  # noqa: E501

        self._molecular_profile_id = molecular_profile_id

    @property
    def study_id(self):
        """Gets the study_id of this MolecularProfile.  # noqa: E501


        :return: The study_id of this MolecularProfile.  # noqa: E501
        :rtype: str
        """
        return self._study_id

    @study_id.setter
    def study_id(self, study_id):
        """Sets the study_id of this MolecularProfile.


        :param study_id: The study_id of this MolecularProfile.  # noqa: E501
        :type: str
        """
        if study_id is None:
            raise ValueError("Invalid value for `study_id`, must not be `None`")  # noqa: E501

        self._study_id = study_id

    @property
    def study(self):
        """Gets the study of this MolecularProfile.  # noqa: E501


        :return: The study of this MolecularProfile.  # noqa: E501
        :rtype: CancerStudy
        """
        return self._study

    @study.setter
    def study(self, study):
        """Sets the study of this MolecularProfile.


        :param study: The study of this MolecularProfile.  # noqa: E501
        :type: CancerStudy
        """

        self._study = study

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MolecularProfile, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MolecularProfile):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
