# coding: utf-8

"""
    cBioPortal web Public API [Alpha]

    A web service for supplying JSON formatted data to cBioPortal clients. Please note that this API is currently in beta and subject to change.  # noqa: E501

    OpenAPI spec version: 1.0 (beta). Backwards compatibility will be maintained (after 1.0 release)
    Contact: cbioportal@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Mutation(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'unique_sample_key': 'str',
        'unique_patient_key': 'str',
        'molecular_profile_id': 'str',
        'sample_id': 'str',
        'patient_id': 'str',
        'entrez_gene_id': 'int',
        'gene': 'Gene',
        'study_id': 'str',
        'driver_filter': 'str',
        'driver_filter_annotation': 'str',
        'driver_tiers_filter': 'str',
        'driver_tiers_filter_annotation': 'str',
        'center': 'str',
        'mutation_status': 'str',
        'validation_status': 'str',
        'tumor_alt_count': 'int',
        'tumor_ref_count': 'int',
        'normal_alt_count': 'int',
        'normal_ref_count': 'int',
        'amino_acid_change': 'str',
        'start_position': 'int',
        'end_position': 'int',
        'reference_allele': 'str',
        'protein_change': 'str',
        'mutation_type': 'str',
        'ncbi_build': 'str',
        'variant_type': 'str',
        'keyword': 'str',
        'allele_specific_copy_number': 'AlleleSpecificCopyNumber',
        'chr': 'str',
        'variant_allele': 'str',
        'refseq_mrna_id': 'str',
        'protein_pos_start': 'int',
        'protein_pos_end': 'int',
        'namespace_columns': 'object'
    }

    attribute_map = {
        'unique_sample_key': 'uniqueSampleKey',
        'unique_patient_key': 'uniquePatientKey',
        'molecular_profile_id': 'molecularProfileId',
        'sample_id': 'sampleId',
        'patient_id': 'patientId',
        'entrez_gene_id': 'entrezGeneId',
        'gene': 'gene',
        'study_id': 'studyId',
        'driver_filter': 'driverFilter',
        'driver_filter_annotation': 'driverFilterAnnotation',
        'driver_tiers_filter': 'driverTiersFilter',
        'driver_tiers_filter_annotation': 'driverTiersFilterAnnotation',
        'center': 'center',
        'mutation_status': 'mutationStatus',
        'validation_status': 'validationStatus',
        'tumor_alt_count': 'tumorAltCount',
        'tumor_ref_count': 'tumorRefCount',
        'normal_alt_count': 'normalAltCount',
        'normal_ref_count': 'normalRefCount',
        'amino_acid_change': 'aminoAcidChange',
        'start_position': 'startPosition',
        'end_position': 'endPosition',
        'reference_allele': 'referenceAllele',
        'protein_change': 'proteinChange',
        'mutation_type': 'mutationType',
        'ncbi_build': 'ncbiBuild',
        'variant_type': 'variantType',
        'keyword': 'keyword',
        'allele_specific_copy_number': 'alleleSpecificCopyNumber',
        'chr': 'chr',
        'variant_allele': 'variantAllele',
        'refseq_mrna_id': 'refseqMrnaId',
        'protein_pos_start': 'proteinPosStart',
        'protein_pos_end': 'proteinPosEnd',
        'namespace_columns': 'namespaceColumns'
    }

    def __init__(self, unique_sample_key=None, unique_patient_key=None, molecular_profile_id=None, sample_id=None, patient_id=None, entrez_gene_id=None, gene=None, study_id=None, driver_filter=None, driver_filter_annotation=None, driver_tiers_filter=None, driver_tiers_filter_annotation=None, center=None, mutation_status=None, validation_status=None, tumor_alt_count=None, tumor_ref_count=None, normal_alt_count=None, normal_ref_count=None, amino_acid_change=None, start_position=None, end_position=None, reference_allele=None, protein_change=None, mutation_type=None, ncbi_build=None, variant_type=None, keyword=None, allele_specific_copy_number=None, chr=None, variant_allele=None, refseq_mrna_id=None, protein_pos_start=None, protein_pos_end=None, namespace_columns=None):  # noqa: E501
        """Mutation - a model defined in Swagger"""  # noqa: E501
        self._unique_sample_key = None
        self._unique_patient_key = None
        self._molecular_profile_id = None
        self._sample_id = None
        self._patient_id = None
        self._entrez_gene_id = None
        self._gene = None
        self._study_id = None
        self._driver_filter = None
        self._driver_filter_annotation = None
        self._driver_tiers_filter = None
        self._driver_tiers_filter_annotation = None
        self._center = None
        self._mutation_status = None
        self._validation_status = None
        self._tumor_alt_count = None
        self._tumor_ref_count = None
        self._normal_alt_count = None
        self._normal_ref_count = None
        self._amino_acid_change = None
        self._start_position = None
        self._end_position = None
        self._reference_allele = None
        self._protein_change = None
        self._mutation_type = None
        self._ncbi_build = None
        self._variant_type = None
        self._keyword = None
        self._allele_specific_copy_number = None
        self._chr = None
        self._variant_allele = None
        self._refseq_mrna_id = None
        self._protein_pos_start = None
        self._protein_pos_end = None
        self._namespace_columns = None
        self.discriminator = None
        if unique_sample_key is not None:
            self.unique_sample_key = unique_sample_key
        if unique_patient_key is not None:
            self.unique_patient_key = unique_patient_key
        self.molecular_profile_id = molecular_profile_id
        self.sample_id = sample_id
        self.patient_id = patient_id
        self.entrez_gene_id = entrez_gene_id
        if gene is not None:
            self.gene = gene
        self.study_id = study_id
        if driver_filter is not None:
            self.driver_filter = driver_filter
        if driver_filter_annotation is not None:
            self.driver_filter_annotation = driver_filter_annotation
        if driver_tiers_filter is not None:
            self.driver_tiers_filter = driver_tiers_filter
        if driver_tiers_filter_annotation is not None:
            self.driver_tiers_filter_annotation = driver_tiers_filter_annotation
        if center is not None:
            self.center = center
        if mutation_status is not None:
            self.mutation_status = mutation_status
        if validation_status is not None:
            self.validation_status = validation_status
        if tumor_alt_count is not None:
            self.tumor_alt_count = tumor_alt_count
        if tumor_ref_count is not None:
            self.tumor_ref_count = tumor_ref_count
        if normal_alt_count is not None:
            self.normal_alt_count = normal_alt_count
        if normal_ref_count is not None:
            self.normal_ref_count = normal_ref_count
        if amino_acid_change is not None:
            self.amino_acid_change = amino_acid_change
        if start_position is not None:
            self.start_position = start_position
        if end_position is not None:
            self.end_position = end_position
        if reference_allele is not None:
            self.reference_allele = reference_allele
        if protein_change is not None:
            self.protein_change = protein_change
        if mutation_type is not None:
            self.mutation_type = mutation_type
        if ncbi_build is not None:
            self.ncbi_build = ncbi_build
        if variant_type is not None:
            self.variant_type = variant_type
        if keyword is not None:
            self.keyword = keyword
        if allele_specific_copy_number is not None:
            self.allele_specific_copy_number = allele_specific_copy_number
        if chr is not None:
            self.chr = chr
        if variant_allele is not None:
            self.variant_allele = variant_allele
        if refseq_mrna_id is not None:
            self.refseq_mrna_id = refseq_mrna_id
        if protein_pos_start is not None:
            self.protein_pos_start = protein_pos_start
        if protein_pos_end is not None:
            self.protein_pos_end = protein_pos_end
        if namespace_columns is not None:
            self.namespace_columns = namespace_columns

    @property
    def unique_sample_key(self):
        """Gets the unique_sample_key of this Mutation.  # noqa: E501


        :return: The unique_sample_key of this Mutation.  # noqa: E501
        :rtype: str
        """
        return self._unique_sample_key

    @unique_sample_key.setter
    def unique_sample_key(self, unique_sample_key):
        """Sets the unique_sample_key of this Mutation.


        :param unique_sample_key: The unique_sample_key of this Mutation.  # noqa: E501
        :type: str
        """

        self._unique_sample_key = unique_sample_key

    @property
    def unique_patient_key(self):
        """Gets the unique_patient_key of this Mutation.  # noqa: E501


        :return: The unique_patient_key of this Mutation.  # noqa: E501
        :rtype: str
        """
        return self._unique_patient_key

    @unique_patient_key.setter
    def unique_patient_key(self, unique_patient_key):
        """Sets the unique_patient_key of this Mutation.


        :param unique_patient_key: The unique_patient_key of this Mutation.  # noqa: E501
        :type: str
        """

        self._unique_patient_key = unique_patient_key

    @property
    def molecular_profile_id(self):
        """Gets the molecular_profile_id of this Mutation.  # noqa: E501


        :return: The molecular_profile_id of this Mutation.  # noqa: E501
        :rtype: str
        """
        return self._molecular_profile_id

    @molecular_profile_id.setter
    def molecular_profile_id(self, molecular_profile_id):
        """Sets the molecular_profile_id of this Mutation.


        :param molecular_profile_id: The molecular_profile_id of this Mutation.  # noqa: E501
        :type: str
        """
        if molecular_profile_id is None:
            raise ValueError("Invalid value for `molecular_profile_id`, must not be `None`")  # noqa: E501

        self._molecular_profile_id = molecular_profile_id

    @property
    def sample_id(self):
        """Gets the sample_id of this Mutation.  # noqa: E501


        :return: The sample_id of this Mutation.  # noqa: E501
        :rtype: str
        """
        return self._sample_id

    @sample_id.setter
    def sample_id(self, sample_id):
        """Sets the sample_id of this Mutation.


        :param sample_id: The sample_id of this Mutation.  # noqa: E501
        :type: str
        """
        if sample_id is None:
            raise ValueError("Invalid value for `sample_id`, must not be `None`")  # noqa: E501

        self._sample_id = sample_id

    @property
    def patient_id(self):
        """Gets the patient_id of this Mutation.  # noqa: E501


        :return: The patient_id of this Mutation.  # noqa: E501
        :rtype: str
        """
        return self._patient_id

    @patient_id.setter
    def patient_id(self, patient_id):
        """Sets the patient_id of this Mutation.


        :param patient_id: The patient_id of this Mutation.  # noqa: E501
        :type: str
        """
        if patient_id is None:
            raise ValueError("Invalid value for `patient_id`, must not be `None`")  # noqa: E501

        self._patient_id = patient_id

    @property
    def entrez_gene_id(self):
        """Gets the entrez_gene_id of this Mutation.  # noqa: E501


        :return: The entrez_gene_id of this Mutation.  # noqa: E501
        :rtype: int
        """
        return self._entrez_gene_id

    @entrez_gene_id.setter
    def entrez_gene_id(self, entrez_gene_id):
        """Sets the entrez_gene_id of this Mutation.


        :param entrez_gene_id: The entrez_gene_id of this Mutation.  # noqa: E501
        :type: int
        """
        if entrez_gene_id is None:
            raise ValueError("Invalid value for `entrez_gene_id`, must not be `None`")  # noqa: E501

        self._entrez_gene_id = entrez_gene_id

    @property
    def gene(self):
        """Gets the gene of this Mutation.  # noqa: E501


        :return: The gene of this Mutation.  # noqa: E501
        :rtype: Gene
        """
        return self._gene

    @gene.setter
    def gene(self, gene):
        """Sets the gene of this Mutation.


        :param gene: The gene of this Mutation.  # noqa: E501
        :type: Gene
        """

        self._gene = gene

    @property
    def study_id(self):
        """Gets the study_id of this Mutation.  # noqa: E501


        :return: The study_id of this Mutation.  # noqa: E501
        :rtype: str
        """
        return self._study_id

    @study_id.setter
    def study_id(self, study_id):
        """Sets the study_id of this Mutation.


        :param study_id: The study_id of this Mutation.  # noqa: E501
        :type: str
        """
        if study_id is None:
            raise ValueError("Invalid value for `study_id`, must not be `None`")  # noqa: E501

        self._study_id = study_id

    @property
    def driver_filter(self):
        """Gets the driver_filter of this Mutation.  # noqa: E501


        :return: The driver_filter of this Mutation.  # noqa: E501
        :rtype: str
        """
        return self._driver_filter

    @driver_filter.setter
    def driver_filter(self, driver_filter):
        """Sets the driver_filter of this Mutation.


        :param driver_filter: The driver_filter of this Mutation.  # noqa: E501
        :type: str
        """

        self._driver_filter = driver_filter

    @property
    def driver_filter_annotation(self):
        """Gets the driver_filter_annotation of this Mutation.  # noqa: E501


        :return: The driver_filter_annotation of this Mutation.  # noqa: E501
        :rtype: str
        """
        return self._driver_filter_annotation

    @driver_filter_annotation.setter
    def driver_filter_annotation(self, driver_filter_annotation):
        """Sets the driver_filter_annotation of this Mutation.


        :param driver_filter_annotation: The driver_filter_annotation of this Mutation.  # noqa: E501
        :type: str
        """

        self._driver_filter_annotation = driver_filter_annotation

    @property
    def driver_tiers_filter(self):
        """Gets the driver_tiers_filter of this Mutation.  # noqa: E501


        :return: The driver_tiers_filter of this Mutation.  # noqa: E501
        :rtype: str
        """
        return self._driver_tiers_filter

    @driver_tiers_filter.setter
    def driver_tiers_filter(self, driver_tiers_filter):
        """Sets the driver_tiers_filter of this Mutation.


        :param driver_tiers_filter: The driver_tiers_filter of this Mutation.  # noqa: E501
        :type: str
        """

        self._driver_tiers_filter = driver_tiers_filter

    @property
    def driver_tiers_filter_annotation(self):
        """Gets the driver_tiers_filter_annotation of this Mutation.  # noqa: E501


        :return: The driver_tiers_filter_annotation of this Mutation.  # noqa: E501
        :rtype: str
        """
        return self._driver_tiers_filter_annotation

    @driver_tiers_filter_annotation.setter
    def driver_tiers_filter_annotation(self, driver_tiers_filter_annotation):
        """Sets the driver_tiers_filter_annotation of this Mutation.


        :param driver_tiers_filter_annotation: The driver_tiers_filter_annotation of this Mutation.  # noqa: E501
        :type: str
        """

        self._driver_tiers_filter_annotation = driver_tiers_filter_annotation

    @property
    def center(self):
        """Gets the center of this Mutation.  # noqa: E501


        :return: The center of this Mutation.  # noqa: E501
        :rtype: str
        """
        return self._center

    @center.setter
    def center(self, center):
        """Sets the center of this Mutation.


        :param center: The center of this Mutation.  # noqa: E501
        :type: str
        """

        self._center = center

    @property
    def mutation_status(self):
        """Gets the mutation_status of this Mutation.  # noqa: E501


        :return: The mutation_status of this Mutation.  # noqa: E501
        :rtype: str
        """
        return self._mutation_status

    @mutation_status.setter
    def mutation_status(self, mutation_status):
        """Sets the mutation_status of this Mutation.


        :param mutation_status: The mutation_status of this Mutation.  # noqa: E501
        :type: str
        """

        self._mutation_status = mutation_status

    @property
    def validation_status(self):
        """Gets the validation_status of this Mutation.  # noqa: E501


        :return: The validation_status of this Mutation.  # noqa: E501
        :rtype: str
        """
        return self._validation_status

    @validation_status.setter
    def validation_status(self, validation_status):
        """Sets the validation_status of this Mutation.


        :param validation_status: The validation_status of this Mutation.  # noqa: E501
        :type: str
        """

        self._validation_status = validation_status

    @property
    def tumor_alt_count(self):
        """Gets the tumor_alt_count of this Mutation.  # noqa: E501


        :return: The tumor_alt_count of this Mutation.  # noqa: E501
        :rtype: int
        """
        return self._tumor_alt_count

    @tumor_alt_count.setter
    def tumor_alt_count(self, tumor_alt_count):
        """Sets the tumor_alt_count of this Mutation.


        :param tumor_alt_count: The tumor_alt_count of this Mutation.  # noqa: E501
        :type: int
        """

        self._tumor_alt_count = tumor_alt_count

    @property
    def tumor_ref_count(self):
        """Gets the tumor_ref_count of this Mutation.  # noqa: E501


        :return: The tumor_ref_count of this Mutation.  # noqa: E501
        :rtype: int
        """
        return self._tumor_ref_count

    @tumor_ref_count.setter
    def tumor_ref_count(self, tumor_ref_count):
        """Sets the tumor_ref_count of this Mutation.


        :param tumor_ref_count: The tumor_ref_count of this Mutation.  # noqa: E501
        :type: int
        """

        self._tumor_ref_count = tumor_ref_count

    @property
    def normal_alt_count(self):
        """Gets the normal_alt_count of this Mutation.  # noqa: E501


        :return: The normal_alt_count of this Mutation.  # noqa: E501
        :rtype: int
        """
        return self._normal_alt_count

    @normal_alt_count.setter
    def normal_alt_count(self, normal_alt_count):
        """Sets the normal_alt_count of this Mutation.


        :param normal_alt_count: The normal_alt_count of this Mutation.  # noqa: E501
        :type: int
        """

        self._normal_alt_count = normal_alt_count

    @property
    def normal_ref_count(self):
        """Gets the normal_ref_count of this Mutation.  # noqa: E501


        :return: The normal_ref_count of this Mutation.  # noqa: E501
        :rtype: int
        """
        return self._normal_ref_count

    @normal_ref_count.setter
    def normal_ref_count(self, normal_ref_count):
        """Sets the normal_ref_count of this Mutation.


        :param normal_ref_count: The normal_ref_count of this Mutation.  # noqa: E501
        :type: int
        """

        self._normal_ref_count = normal_ref_count

    @property
    def amino_acid_change(self):
        """Gets the amino_acid_change of this Mutation.  # noqa: E501


        :return: The amino_acid_change of this Mutation.  # noqa: E501
        :rtype: str
        """
        return self._amino_acid_change

    @amino_acid_change.setter
    def amino_acid_change(self, amino_acid_change):
        """Sets the amino_acid_change of this Mutation.


        :param amino_acid_change: The amino_acid_change of this Mutation.  # noqa: E501
        :type: str
        """

        self._amino_acid_change = amino_acid_change

    @property
    def start_position(self):
        """Gets the start_position of this Mutation.  # noqa: E501


        :return: The start_position of this Mutation.  # noqa: E501
        :rtype: int
        """
        return self._start_position

    @start_position.setter
    def start_position(self, start_position):
        """Sets the start_position of this Mutation.


        :param start_position: The start_position of this Mutation.  # noqa: E501
        :type: int
        """

        self._start_position = start_position

    @property
    def end_position(self):
        """Gets the end_position of this Mutation.  # noqa: E501


        :return: The end_position of this Mutation.  # noqa: E501
        :rtype: int
        """
        return self._end_position

    @end_position.setter
    def end_position(self, end_position):
        """Sets the end_position of this Mutation.


        :param end_position: The end_position of this Mutation.  # noqa: E501
        :type: int
        """

        self._end_position = end_position

    @property
    def reference_allele(self):
        """Gets the reference_allele of this Mutation.  # noqa: E501


        :return: The reference_allele of this Mutation.  # noqa: E501
        :rtype: str
        """
        return self._reference_allele

    @reference_allele.setter
    def reference_allele(self, reference_allele):
        """Sets the reference_allele of this Mutation.


        :param reference_allele: The reference_allele of this Mutation.  # noqa: E501
        :type: str
        """

        self._reference_allele = reference_allele

    @property
    def protein_change(self):
        """Gets the protein_change of this Mutation.  # noqa: E501


        :return: The protein_change of this Mutation.  # noqa: E501
        :rtype: str
        """
        return self._protein_change

    @protein_change.setter
    def protein_change(self, protein_change):
        """Sets the protein_change of this Mutation.


        :param protein_change: The protein_change of this Mutation.  # noqa: E501
        :type: str
        """

        self._protein_change = protein_change

    @property
    def mutation_type(self):
        """Gets the mutation_type of this Mutation.  # noqa: E501


        :return: The mutation_type of this Mutation.  # noqa: E501
        :rtype: str
        """
        return self._mutation_type

    @mutation_type.setter
    def mutation_type(self, mutation_type):
        """Sets the mutation_type of this Mutation.


        :param mutation_type: The mutation_type of this Mutation.  # noqa: E501
        :type: str
        """

        self._mutation_type = mutation_type

    @property
    def ncbi_build(self):
        """Gets the ncbi_build of this Mutation.  # noqa: E501


        :return: The ncbi_build of this Mutation.  # noqa: E501
        :rtype: str
        """
        return self._ncbi_build

    @ncbi_build.setter
    def ncbi_build(self, ncbi_build):
        """Sets the ncbi_build of this Mutation.


        :param ncbi_build: The ncbi_build of this Mutation.  # noqa: E501
        :type: str
        """

        self._ncbi_build = ncbi_build

    @property
    def variant_type(self):
        """Gets the variant_type of this Mutation.  # noqa: E501


        :return: The variant_type of this Mutation.  # noqa: E501
        :rtype: str
        """
        return self._variant_type

    @variant_type.setter
    def variant_type(self, variant_type):
        """Sets the variant_type of this Mutation.


        :param variant_type: The variant_type of this Mutation.  # noqa: E501
        :type: str
        """

        self._variant_type = variant_type

    @property
    def keyword(self):
        """Gets the keyword of this Mutation.  # noqa: E501


        :return: The keyword of this Mutation.  # noqa: E501
        :rtype: str
        """
        return self._keyword

    @keyword.setter
    def keyword(self, keyword):
        """Sets the keyword of this Mutation.


        :param keyword: The keyword of this Mutation.  # noqa: E501
        :type: str
        """

        self._keyword = keyword

    @property
    def allele_specific_copy_number(self):
        """Gets the allele_specific_copy_number of this Mutation.  # noqa: E501


        :return: The allele_specific_copy_number of this Mutation.  # noqa: E501
        :rtype: AlleleSpecificCopyNumber
        """
        return self._allele_specific_copy_number

    @allele_specific_copy_number.setter
    def allele_specific_copy_number(self, allele_specific_copy_number):
        """Sets the allele_specific_copy_number of this Mutation.


        :param allele_specific_copy_number: The allele_specific_copy_number of this Mutation.  # noqa: E501
        :type: AlleleSpecificCopyNumber
        """

        self._allele_specific_copy_number = allele_specific_copy_number

    @property
    def chr(self):
        """Gets the chr of this Mutation.  # noqa: E501


        :return: The chr of this Mutation.  # noqa: E501
        :rtype: str
        """
        return self._chr

    @chr.setter
    def chr(self, chr):
        """Sets the chr of this Mutation.


        :param chr: The chr of this Mutation.  # noqa: E501
        :type: str
        """

        self._chr = chr

    @property
    def variant_allele(self):
        """Gets the variant_allele of this Mutation.  # noqa: E501


        :return: The variant_allele of this Mutation.  # noqa: E501
        :rtype: str
        """
        return self._variant_allele

    @variant_allele.setter
    def variant_allele(self, variant_allele):
        """Sets the variant_allele of this Mutation.


        :param variant_allele: The variant_allele of this Mutation.  # noqa: E501
        :type: str
        """

        self._variant_allele = variant_allele

    @property
    def refseq_mrna_id(self):
        """Gets the refseq_mrna_id of this Mutation.  # noqa: E501


        :return: The refseq_mrna_id of this Mutation.  # noqa: E501
        :rtype: str
        """
        return self._refseq_mrna_id

    @refseq_mrna_id.setter
    def refseq_mrna_id(self, refseq_mrna_id):
        """Sets the refseq_mrna_id of this Mutation.


        :param refseq_mrna_id: The refseq_mrna_id of this Mutation.  # noqa: E501
        :type: str
        """

        self._refseq_mrna_id = refseq_mrna_id

    @property
    def protein_pos_start(self):
        """Gets the protein_pos_start of this Mutation.  # noqa: E501


        :return: The protein_pos_start of this Mutation.  # noqa: E501
        :rtype: int
        """
        return self._protein_pos_start

    @protein_pos_start.setter
    def protein_pos_start(self, protein_pos_start):
        """Sets the protein_pos_start of this Mutation.


        :param protein_pos_start: The protein_pos_start of this Mutation.  # noqa: E501
        :type: int
        """

        self._protein_pos_start = protein_pos_start

    @property
    def protein_pos_end(self):
        """Gets the protein_pos_end of this Mutation.  # noqa: E501


        :return: The protein_pos_end of this Mutation.  # noqa: E501
        :rtype: int
        """
        return self._protein_pos_end

    @protein_pos_end.setter
    def protein_pos_end(self, protein_pos_end):
        """Sets the protein_pos_end of this Mutation.


        :param protein_pos_end: The protein_pos_end of this Mutation.  # noqa: E501
        :type: int
        """

        self._protein_pos_end = protein_pos_end

    @property
    def namespace_columns(self):
        """Gets the namespace_columns of this Mutation.  # noqa: E501


        :return: The namespace_columns of this Mutation.  # noqa: E501
        :rtype: object
        """
        return self._namespace_columns

    @namespace_columns.setter
    def namespace_columns(self, namespace_columns):
        """Sets the namespace_columns of this Mutation.


        :param namespace_columns: The namespace_columns of this Mutation.  # noqa: E501
        :type: object
        """

        self._namespace_columns = namespace_columns

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Mutation, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Mutation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
