# coding: utf-8

"""
    cBioPortal web Public API [Alpha]

    A web service for supplying JSON formatted data to cBioPortal clients. Please note that this API is currently in beta and subject to change.  # noqa: E501

    OpenAPI spec version: 1.0 (beta). Backwards compatibility will be maintained (after 1.0 release)
    Contact: cbioportal@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MutationMultipleStudyFilter(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'sample_molecular_identifiers': 'list[SampleMolecularIdentifier]',
        'molecular_profile_ids': 'list[str]',
        'entrez_gene_ids': 'list[int]'
    }

    attribute_map = {
        'sample_molecular_identifiers': 'sampleMolecularIdentifiers',
        'molecular_profile_ids': 'molecularProfileIds',
        'entrez_gene_ids': 'entrezGeneIds'
    }

    def __init__(self, sample_molecular_identifiers=None, molecular_profile_ids=None, entrez_gene_ids=None):  # noqa: E501
        """MutationMultipleStudyFilter - a model defined in Swagger"""  # noqa: E501
        self._sample_molecular_identifiers = None
        self._molecular_profile_ids = None
        self._entrez_gene_ids = None
        self.discriminator = None
        if sample_molecular_identifiers is not None:
            self.sample_molecular_identifiers = sample_molecular_identifiers
        if molecular_profile_ids is not None:
            self.molecular_profile_ids = molecular_profile_ids
        if entrez_gene_ids is not None:
            self.entrez_gene_ids = entrez_gene_ids

    @property
    def sample_molecular_identifiers(self):
        """Gets the sample_molecular_identifiers of this MutationMultipleStudyFilter.  # noqa: E501


        :return: The sample_molecular_identifiers of this MutationMultipleStudyFilter.  # noqa: E501
        :rtype: list[SampleMolecularIdentifier]
        """
        return self._sample_molecular_identifiers

    @sample_molecular_identifiers.setter
    def sample_molecular_identifiers(self, sample_molecular_identifiers):
        """Sets the sample_molecular_identifiers of this MutationMultipleStudyFilter.


        :param sample_molecular_identifiers: The sample_molecular_identifiers of this MutationMultipleStudyFilter.  # noqa: E501
        :type: list[SampleMolecularIdentifier]
        """

        self._sample_molecular_identifiers = sample_molecular_identifiers

    @property
    def molecular_profile_ids(self):
        """Gets the molecular_profile_ids of this MutationMultipleStudyFilter.  # noqa: E501


        :return: The molecular_profile_ids of this MutationMultipleStudyFilter.  # noqa: E501
        :rtype: list[str]
        """
        return self._molecular_profile_ids

    @molecular_profile_ids.setter
    def molecular_profile_ids(self, molecular_profile_ids):
        """Sets the molecular_profile_ids of this MutationMultipleStudyFilter.


        :param molecular_profile_ids: The molecular_profile_ids of this MutationMultipleStudyFilter.  # noqa: E501
        :type: list[str]
        """

        self._molecular_profile_ids = molecular_profile_ids

    @property
    def entrez_gene_ids(self):
        """Gets the entrez_gene_ids of this MutationMultipleStudyFilter.  # noqa: E501


        :return: The entrez_gene_ids of this MutationMultipleStudyFilter.  # noqa: E501
        :rtype: list[int]
        """
        return self._entrez_gene_ids

    @entrez_gene_ids.setter
    def entrez_gene_ids(self, entrez_gene_ids):
        """Sets the entrez_gene_ids of this MutationMultipleStudyFilter.


        :param entrez_gene_ids: The entrez_gene_ids of this MutationMultipleStudyFilter.  # noqa: E501
        :type: list[int]
        """

        self._entrez_gene_ids = entrez_gene_ids

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MutationMultipleStudyFilter, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MutationMultipleStudyFilter):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
