# coding: utf-8

"""
    cBioPortal web Public API [Alpha]

    A web service for supplying JSON formatted data to cBioPortal clients. Please note that this API is currently in beta and subject to change.  # noqa: E501

    OpenAPI spec version: 1.0 (beta). Backwards compatibility will be maintained (after 1.0 release)
    Contact: cbioportal@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class NamespaceAttribute(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'outer_key': 'str',
        'inner_key': 'str'
    }

    attribute_map = {
        'outer_key': 'outerKey',
        'inner_key': 'innerKey'
    }

    def __init__(self, outer_key=None, inner_key=None):  # noqa: E501
        """NamespaceAttribute - a model defined in Swagger"""  # noqa: E501
        self._outer_key = None
        self._inner_key = None
        self.discriminator = None
        if outer_key is not None:
            self.outer_key = outer_key
        if inner_key is not None:
            self.inner_key = inner_key

    @property
    def outer_key(self):
        """Gets the outer_key of this NamespaceAttribute.  # noqa: E501


        :return: The outer_key of this NamespaceAttribute.  # noqa: E501
        :rtype: str
        """
        return self._outer_key

    @outer_key.setter
    def outer_key(self, outer_key):
        """Sets the outer_key of this NamespaceAttribute.


        :param outer_key: The outer_key of this NamespaceAttribute.  # noqa: E501
        :type: str
        """

        self._outer_key = outer_key

    @property
    def inner_key(self):
        """Gets the inner_key of this NamespaceAttribute.  # noqa: E501


        :return: The inner_key of this NamespaceAttribute.  # noqa: E501
        :rtype: str
        """
        return self._inner_key

    @inner_key.setter
    def inner_key(self, inner_key):
        """Sets the inner_key of this NamespaceAttribute.


        :param inner_key: The inner_key of this NamespaceAttribute.  # noqa: E501
        :type: str
        """

        self._inner_key = inner_key

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(NamespaceAttribute, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NamespaceAttribute):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
