# coding: utf-8

"""
    cBioPortal web Public API [Alpha]

    A web service for supplying JSON formatted data to cBioPortal clients. Please note that this API is currently in beta and subject to change.  # noqa: E501

    OpenAPI spec version: 1.0 (beta). Backwards compatibility will be maintained (after 1.0 release)
    Contact: cbioportal@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class NumericGeneMolecularData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'unique_sample_key': 'str',
        'unique_patient_key': 'str',
        'entrez_gene_id': 'int',
        'gene': 'Gene',
        'molecular_profile_id': 'str',
        'sample_id': 'str',
        'patient_id': 'str',
        'study_id': 'str',
        'value': 'float'
    }

    attribute_map = {
        'unique_sample_key': 'uniqueSampleKey',
        'unique_patient_key': 'uniquePatientKey',
        'entrez_gene_id': 'entrezGeneId',
        'gene': 'gene',
        'molecular_profile_id': 'molecularProfileId',
        'sample_id': 'sampleId',
        'patient_id': 'patientId',
        'study_id': 'studyId',
        'value': 'value'
    }

    def __init__(self, unique_sample_key=None, unique_patient_key=None, entrez_gene_id=None, gene=None, molecular_profile_id=None, sample_id=None, patient_id=None, study_id=None, value=None):  # noqa: E501
        """NumericGeneMolecularData - a model defined in Swagger"""  # noqa: E501
        self._unique_sample_key = None
        self._unique_patient_key = None
        self._entrez_gene_id = None
        self._gene = None
        self._molecular_profile_id = None
        self._sample_id = None
        self._patient_id = None
        self._study_id = None
        self._value = None
        self.discriminator = None
        if unique_sample_key is not None:
            self.unique_sample_key = unique_sample_key
        if unique_patient_key is not None:
            self.unique_patient_key = unique_patient_key
        self.entrez_gene_id = entrez_gene_id
        if gene is not None:
            self.gene = gene
        self.molecular_profile_id = molecular_profile_id
        self.sample_id = sample_id
        self.patient_id = patient_id
        self.study_id = study_id
        self.value = value

    @property
    def unique_sample_key(self):
        """Gets the unique_sample_key of this NumericGeneMolecularData.  # noqa: E501


        :return: The unique_sample_key of this NumericGeneMolecularData.  # noqa: E501
        :rtype: str
        """
        return self._unique_sample_key

    @unique_sample_key.setter
    def unique_sample_key(self, unique_sample_key):
        """Sets the unique_sample_key of this NumericGeneMolecularData.


        :param unique_sample_key: The unique_sample_key of this NumericGeneMolecularData.  # noqa: E501
        :type: str
        """

        self._unique_sample_key = unique_sample_key

    @property
    def unique_patient_key(self):
        """Gets the unique_patient_key of this NumericGeneMolecularData.  # noqa: E501


        :return: The unique_patient_key of this NumericGeneMolecularData.  # noqa: E501
        :rtype: str
        """
        return self._unique_patient_key

    @unique_patient_key.setter
    def unique_patient_key(self, unique_patient_key):
        """Sets the unique_patient_key of this NumericGeneMolecularData.


        :param unique_patient_key: The unique_patient_key of this NumericGeneMolecularData.  # noqa: E501
        :type: str
        """

        self._unique_patient_key = unique_patient_key

    @property
    def entrez_gene_id(self):
        """Gets the entrez_gene_id of this NumericGeneMolecularData.  # noqa: E501


        :return: The entrez_gene_id of this NumericGeneMolecularData.  # noqa: E501
        :rtype: int
        """
        return self._entrez_gene_id

    @entrez_gene_id.setter
    def entrez_gene_id(self, entrez_gene_id):
        """Sets the entrez_gene_id of this NumericGeneMolecularData.


        :param entrez_gene_id: The entrez_gene_id of this NumericGeneMolecularData.  # noqa: E501
        :type: int
        """
        if entrez_gene_id is None:
            raise ValueError("Invalid value for `entrez_gene_id`, must not be `None`")  # noqa: E501

        self._entrez_gene_id = entrez_gene_id

    @property
    def gene(self):
        """Gets the gene of this NumericGeneMolecularData.  # noqa: E501


        :return: The gene of this NumericGeneMolecularData.  # noqa: E501
        :rtype: Gene
        """
        return self._gene

    @gene.setter
    def gene(self, gene):
        """Sets the gene of this NumericGeneMolecularData.


        :param gene: The gene of this NumericGeneMolecularData.  # noqa: E501
        :type: Gene
        """

        self._gene = gene

    @property
    def molecular_profile_id(self):
        """Gets the molecular_profile_id of this NumericGeneMolecularData.  # noqa: E501


        :return: The molecular_profile_id of this NumericGeneMolecularData.  # noqa: E501
        :rtype: str
        """
        return self._molecular_profile_id

    @molecular_profile_id.setter
    def molecular_profile_id(self, molecular_profile_id):
        """Sets the molecular_profile_id of this NumericGeneMolecularData.


        :param molecular_profile_id: The molecular_profile_id of this NumericGeneMolecularData.  # noqa: E501
        :type: str
        """
        if molecular_profile_id is None:
            raise ValueError("Invalid value for `molecular_profile_id`, must not be `None`")  # noqa: E501

        self._molecular_profile_id = molecular_profile_id

    @property
    def sample_id(self):
        """Gets the sample_id of this NumericGeneMolecularData.  # noqa: E501


        :return: The sample_id of this NumericGeneMolecularData.  # noqa: E501
        :rtype: str
        """
        return self._sample_id

    @sample_id.setter
    def sample_id(self, sample_id):
        """Sets the sample_id of this NumericGeneMolecularData.


        :param sample_id: The sample_id of this NumericGeneMolecularData.  # noqa: E501
        :type: str
        """
        if sample_id is None:
            raise ValueError("Invalid value for `sample_id`, must not be `None`")  # noqa: E501

        self._sample_id = sample_id

    @property
    def patient_id(self):
        """Gets the patient_id of this NumericGeneMolecularData.  # noqa: E501


        :return: The patient_id of this NumericGeneMolecularData.  # noqa: E501
        :rtype: str
        """
        return self._patient_id

    @patient_id.setter
    def patient_id(self, patient_id):
        """Sets the patient_id of this NumericGeneMolecularData.


        :param patient_id: The patient_id of this NumericGeneMolecularData.  # noqa: E501
        :type: str
        """
        if patient_id is None:
            raise ValueError("Invalid value for `patient_id`, must not be `None`")  # noqa: E501

        self._patient_id = patient_id

    @property
    def study_id(self):
        """Gets the study_id of this NumericGeneMolecularData.  # noqa: E501


        :return: The study_id of this NumericGeneMolecularData.  # noqa: E501
        :rtype: str
        """
        return self._study_id

    @study_id.setter
    def study_id(self, study_id):
        """Sets the study_id of this NumericGeneMolecularData.


        :param study_id: The study_id of this NumericGeneMolecularData.  # noqa: E501
        :type: str
        """
        if study_id is None:
            raise ValueError("Invalid value for `study_id`, must not be `None`")  # noqa: E501

        self._study_id = study_id

    @property
    def value(self):
        """Gets the value of this NumericGeneMolecularData.  # noqa: E501


        :return: The value of this NumericGeneMolecularData.  # noqa: E501
        :rtype: float
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this NumericGeneMolecularData.


        :param value: The value of this NumericGeneMolecularData.  # noqa: E501
        :type: float
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(NumericGeneMolecularData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NumericGeneMolecularData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
