# coding: utf-8

"""
    cBioPortal web Public API [Alpha]

    A web service for supplying JSON formatted data to cBioPortal clients. Please note that this API is currently in beta and subject to change.  # noqa: E501

    OpenAPI spec version: 1.0 (beta). Backwards compatibility will be maintained (after 1.0 release)
    Contact: cbioportal@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PatientFilter(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'patient_identifiers': 'list[PatientIdentifier]',
        'unique_patient_keys': 'list[str]'
    }

    attribute_map = {
        'patient_identifiers': 'patientIdentifiers',
        'unique_patient_keys': 'uniquePatientKeys'
    }

    def __init__(self, patient_identifiers=None, unique_patient_keys=None):  # noqa: E501
        """PatientFilter - a model defined in Swagger"""  # noqa: E501
        self._patient_identifiers = None
        self._unique_patient_keys = None
        self.discriminator = None
        if patient_identifiers is not None:
            self.patient_identifiers = patient_identifiers
        if unique_patient_keys is not None:
            self.unique_patient_keys = unique_patient_keys

    @property
    def patient_identifiers(self):
        """Gets the patient_identifiers of this PatientFilter.  # noqa: E501


        :return: The patient_identifiers of this PatientFilter.  # noqa: E501
        :rtype: list[PatientIdentifier]
        """
        return self._patient_identifiers

    @patient_identifiers.setter
    def patient_identifiers(self, patient_identifiers):
        """Sets the patient_identifiers of this PatientFilter.


        :param patient_identifiers: The patient_identifiers of this PatientFilter.  # noqa: E501
        :type: list[PatientIdentifier]
        """

        self._patient_identifiers = patient_identifiers

    @property
    def unique_patient_keys(self):
        """Gets the unique_patient_keys of this PatientFilter.  # noqa: E501


        :return: The unique_patient_keys of this PatientFilter.  # noqa: E501
        :rtype: list[str]
        """
        return self._unique_patient_keys

    @unique_patient_keys.setter
    def unique_patient_keys(self, unique_patient_keys):
        """Sets the unique_patient_keys of this PatientFilter.


        :param unique_patient_keys: The unique_patient_keys of this PatientFilter.  # noqa: E501
        :type: list[str]
        """

        self._unique_patient_keys = unique_patient_keys

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PatientFilter, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PatientFilter):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
