# coding: utf-8

"""
    cBioPortal web Public API [Alpha]

    A web service for supplying JSON formatted data to cBioPortal clients. Please note that this API is currently in beta and subject to change.  # noqa: E501

    OpenAPI spec version: 1.0 (beta). Backwards compatibility will be maintained (after 1.0 release)
    Contact: cbioportal@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Patient(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'unique_sample_key': 'str',
        'unique_patient_key': 'str',
        'cancer_study': 'CancerStudy',
        'patient_id': 'str',
        'study_id': 'str'
    }

    attribute_map = {
        'unique_sample_key': 'uniqueSampleKey',
        'unique_patient_key': 'uniquePatientKey',
        'cancer_study': 'cancerStudy',
        'patient_id': 'patientId',
        'study_id': 'studyId'
    }

    def __init__(self, unique_sample_key=None, unique_patient_key=None, cancer_study=None, patient_id=None, study_id=None):  # noqa: E501
        """Patient - a model defined in Swagger"""  # noqa: E501
        self._unique_sample_key = None
        self._unique_patient_key = None
        self._cancer_study = None
        self._patient_id = None
        self._study_id = None
        self.discriminator = None
        if unique_sample_key is not None:
            self.unique_sample_key = unique_sample_key
        if unique_patient_key is not None:
            self.unique_patient_key = unique_patient_key
        if cancer_study is not None:
            self.cancer_study = cancer_study
        self.patient_id = patient_id
        self.study_id = study_id

    @property
    def unique_sample_key(self):
        """Gets the unique_sample_key of this Patient.  # noqa: E501


        :return: The unique_sample_key of this Patient.  # noqa: E501
        :rtype: str
        """
        return self._unique_sample_key

    @unique_sample_key.setter
    def unique_sample_key(self, unique_sample_key):
        """Sets the unique_sample_key of this Patient.


        :param unique_sample_key: The unique_sample_key of this Patient.  # noqa: E501
        :type: str
        """

        self._unique_sample_key = unique_sample_key

    @property
    def unique_patient_key(self):
        """Gets the unique_patient_key of this Patient.  # noqa: E501


        :return: The unique_patient_key of this Patient.  # noqa: E501
        :rtype: str
        """
        return self._unique_patient_key

    @unique_patient_key.setter
    def unique_patient_key(self, unique_patient_key):
        """Sets the unique_patient_key of this Patient.


        :param unique_patient_key: The unique_patient_key of this Patient.  # noqa: E501
        :type: str
        """

        self._unique_patient_key = unique_patient_key

    @property
    def cancer_study(self):
        """Gets the cancer_study of this Patient.  # noqa: E501


        :return: The cancer_study of this Patient.  # noqa: E501
        :rtype: CancerStudy
        """
        return self._cancer_study

    @cancer_study.setter
    def cancer_study(self, cancer_study):
        """Sets the cancer_study of this Patient.


        :param cancer_study: The cancer_study of this Patient.  # noqa: E501
        :type: CancerStudy
        """

        self._cancer_study = cancer_study

    @property
    def patient_id(self):
        """Gets the patient_id of this Patient.  # noqa: E501


        :return: The patient_id of this Patient.  # noqa: E501
        :rtype: str
        """
        return self._patient_id

    @patient_id.setter
    def patient_id(self, patient_id):
        """Sets the patient_id of this Patient.


        :param patient_id: The patient_id of this Patient.  # noqa: E501
        :type: str
        """
        if patient_id is None:
            raise ValueError("Invalid value for `patient_id`, must not be `None`")  # noqa: E501

        self._patient_id = patient_id

    @property
    def study_id(self):
        """Gets the study_id of this Patient.  # noqa: E501


        :return: The study_id of this Patient.  # noqa: E501
        :rtype: str
        """
        return self._study_id

    @study_id.setter
    def study_id(self, study_id):
        """Sets the study_id of this Patient.


        :param study_id: The study_id of this Patient.  # noqa: E501
        :type: str
        """
        if study_id is None:
            raise ValueError("Invalid value for `study_id`, must not be `None`")  # noqa: E501

        self._study_id = study_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Patient, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Patient):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
