# coding: utf-8

"""
    cBioPortal web Public API [Alpha]

    A web service for supplying JSON formatted data to cBioPortal clients. Please note that this API is currently in beta and subject to change.  # noqa: E501

    OpenAPI spec version: 1.0 (beta). Backwards compatibility will be maintained (after 1.0 release)
    Contact: cbioportal@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ResourceCount(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'resource_id': 'str',
        'display_name': 'str',
        'description': 'str',
        'resource_type': 'str',
        'priority': 'str',
        'open_by_default': 'bool',
        'custom_meta_data': 'str',
        'sample_count': 'int',
        'patient_count': 'int',
        'study_id': 'str'
    }

    attribute_map = {
        'resource_id': 'resourceId',
        'display_name': 'displayName',
        'description': 'description',
        'resource_type': 'resourceType',
        'priority': 'priority',
        'open_by_default': 'openByDefault',
        'custom_meta_data': 'customMetaData',
        'sample_count': 'sampleCount',
        'patient_count': 'patientCount',
        'study_id': 'studyId'
    }

    def __init__(self, resource_id=None, display_name=None, description=None, resource_type=None, priority=None, open_by_default=None, custom_meta_data=None, sample_count=None, patient_count=None, study_id=None):  # noqa: E501
        """ResourceCount - a model defined in Swagger"""  # noqa: E501
        self._resource_id = None
        self._display_name = None
        self._description = None
        self._resource_type = None
        self._priority = None
        self._open_by_default = None
        self._custom_meta_data = None
        self._sample_count = None
        self._patient_count = None
        self._study_id = None
        self.discriminator = None
        self.resource_id = resource_id
        self.display_name = display_name
        if description is not None:
            self.description = description
        self.resource_type = resource_type
        if priority is not None:
            self.priority = priority
        if open_by_default is not None:
            self.open_by_default = open_by_default
        if custom_meta_data is not None:
            self.custom_meta_data = custom_meta_data
        if sample_count is not None:
            self.sample_count = sample_count
        if patient_count is not None:
            self.patient_count = patient_count
        self.study_id = study_id

    @property
    def resource_id(self):
        """Gets the resource_id of this ResourceCount.  # noqa: E501


        :return: The resource_id of this ResourceCount.  # noqa: E501
        :rtype: str
        """
        return self._resource_id

    @resource_id.setter
    def resource_id(self, resource_id):
        """Sets the resource_id of this ResourceCount.


        :param resource_id: The resource_id of this ResourceCount.  # noqa: E501
        :type: str
        """
        if resource_id is None:
            raise ValueError("Invalid value for `resource_id`, must not be `None`")  # noqa: E501

        self._resource_id = resource_id

    @property
    def display_name(self):
        """Gets the display_name of this ResourceCount.  # noqa: E501


        :return: The display_name of this ResourceCount.  # noqa: E501
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """Sets the display_name of this ResourceCount.


        :param display_name: The display_name of this ResourceCount.  # noqa: E501
        :type: str
        """
        if display_name is None:
            raise ValueError("Invalid value for `display_name`, must not be `None`")  # noqa: E501

        self._display_name = display_name

    @property
    def description(self):
        """Gets the description of this ResourceCount.  # noqa: E501


        :return: The description of this ResourceCount.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ResourceCount.


        :param description: The description of this ResourceCount.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def resource_type(self):
        """Gets the resource_type of this ResourceCount.  # noqa: E501


        :return: The resource_type of this ResourceCount.  # noqa: E501
        :rtype: str
        """
        return self._resource_type

    @resource_type.setter
    def resource_type(self, resource_type):
        """Sets the resource_type of this ResourceCount.


        :param resource_type: The resource_type of this ResourceCount.  # noqa: E501
        :type: str
        """
        if resource_type is None:
            raise ValueError("Invalid value for `resource_type`, must not be `None`")  # noqa: E501
        allowed_values = ["STUDY", "SAMPLE", "PATIENT"]  # noqa: E501
        if resource_type not in allowed_values:
            raise ValueError(
                "Invalid value for `resource_type` ({0}), must be one of {1}"  # noqa: E501
                .format(resource_type, allowed_values)
            )

        self._resource_type = resource_type

    @property
    def priority(self):
        """Gets the priority of this ResourceCount.  # noqa: E501


        :return: The priority of this ResourceCount.  # noqa: E501
        :rtype: str
        """
        return self._priority

    @priority.setter
    def priority(self, priority):
        """Sets the priority of this ResourceCount.


        :param priority: The priority of this ResourceCount.  # noqa: E501
        :type: str
        """

        self._priority = priority

    @property
    def open_by_default(self):
        """Gets the open_by_default of this ResourceCount.  # noqa: E501


        :return: The open_by_default of this ResourceCount.  # noqa: E501
        :rtype: bool
        """
        return self._open_by_default

    @open_by_default.setter
    def open_by_default(self, open_by_default):
        """Sets the open_by_default of this ResourceCount.


        :param open_by_default: The open_by_default of this ResourceCount.  # noqa: E501
        :type: bool
        """

        self._open_by_default = open_by_default

    @property
    def custom_meta_data(self):
        """Gets the custom_meta_data of this ResourceCount.  # noqa: E501


        :return: The custom_meta_data of this ResourceCount.  # noqa: E501
        :rtype: str
        """
        return self._custom_meta_data

    @custom_meta_data.setter
    def custom_meta_data(self, custom_meta_data):
        """Sets the custom_meta_data of this ResourceCount.


        :param custom_meta_data: The custom_meta_data of this ResourceCount.  # noqa: E501
        :type: str
        """

        self._custom_meta_data = custom_meta_data

    @property
    def sample_count(self):
        """Gets the sample_count of this ResourceCount.  # noqa: E501


        :return: The sample_count of this ResourceCount.  # noqa: E501
        :rtype: int
        """
        return self._sample_count

    @sample_count.setter
    def sample_count(self, sample_count):
        """Sets the sample_count of this ResourceCount.


        :param sample_count: The sample_count of this ResourceCount.  # noqa: E501
        :type: int
        """

        self._sample_count = sample_count

    @property
    def patient_count(self):
        """Gets the patient_count of this ResourceCount.  # noqa: E501


        :return: The patient_count of this ResourceCount.  # noqa: E501
        :rtype: int
        """
        return self._patient_count

    @patient_count.setter
    def patient_count(self, patient_count):
        """Sets the patient_count of this ResourceCount.


        :param patient_count: The patient_count of this ResourceCount.  # noqa: E501
        :type: int
        """

        self._patient_count = patient_count

    @property
    def study_id(self):
        """Gets the study_id of this ResourceCount.  # noqa: E501


        :return: The study_id of this ResourceCount.  # noqa: E501
        :rtype: str
        """
        return self._study_id

    @study_id.setter
    def study_id(self, study_id):
        """Sets the study_id of this ResourceCount.


        :param study_id: The study_id of this ResourceCount.  # noqa: E501
        :type: str
        """
        if study_id is None:
            raise ValueError("Invalid value for `study_id`, must not be `None`")  # noqa: E501

        self._study_id = study_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ResourceCount, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ResourceCount):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
