# coding: utf-8

"""
    cBioPortal web Public API [Alpha]

    A web service for supplying JSON formatted data to cBioPortal clients. Please note that this API is currently in beta and subject to change.  # noqa: E501

    OpenAPI spec version: 1.0 (beta). Backwards compatibility will be maintained (after 1.0 release)
    Contact: cbioportal@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SampleList(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'category': 'str',
        'name': 'str',
        'description': 'str',
        'sample_count': 'int',
        'sample_ids': 'list[str]',
        'sample_list_id': 'str',
        'study_id': 'str'
    }

    attribute_map = {
        'category': 'category',
        'name': 'name',
        'description': 'description',
        'sample_count': 'sampleCount',
        'sample_ids': 'sampleIds',
        'sample_list_id': 'sampleListId',
        'study_id': 'studyId'
    }

    def __init__(self, category=None, name=None, description=None, sample_count=None, sample_ids=None, sample_list_id=None, study_id=None):  # noqa: E501
        """SampleList - a model defined in Swagger"""  # noqa: E501
        self._category = None
        self._name = None
        self._description = None
        self._sample_count = None
        self._sample_ids = None
        self._sample_list_id = None
        self._study_id = None
        self.discriminator = None
        if category is not None:
            self.category = category
        if name is not None:
            self.name = name
        if description is not None:
            self.description = description
        if sample_count is not None:
            self.sample_count = sample_count
        if sample_ids is not None:
            self.sample_ids = sample_ids
        self.sample_list_id = sample_list_id
        if study_id is not None:
            self.study_id = study_id

    @property
    def category(self):
        """Gets the category of this SampleList.  # noqa: E501


        :return: The category of this SampleList.  # noqa: E501
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category):
        """Sets the category of this SampleList.


        :param category: The category of this SampleList.  # noqa: E501
        :type: str
        """

        self._category = category

    @property
    def name(self):
        """Gets the name of this SampleList.  # noqa: E501


        :return: The name of this SampleList.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SampleList.


        :param name: The name of this SampleList.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """Gets the description of this SampleList.  # noqa: E501


        :return: The description of this SampleList.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this SampleList.


        :param description: The description of this SampleList.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def sample_count(self):
        """Gets the sample_count of this SampleList.  # noqa: E501


        :return: The sample_count of this SampleList.  # noqa: E501
        :rtype: int
        """
        return self._sample_count

    @sample_count.setter
    def sample_count(self, sample_count):
        """Sets the sample_count of this SampleList.


        :param sample_count: The sample_count of this SampleList.  # noqa: E501
        :type: int
        """

        self._sample_count = sample_count

    @property
    def sample_ids(self):
        """Gets the sample_ids of this SampleList.  # noqa: E501


        :return: The sample_ids of this SampleList.  # noqa: E501
        :rtype: list[str]
        """
        return self._sample_ids

    @sample_ids.setter
    def sample_ids(self, sample_ids):
        """Sets the sample_ids of this SampleList.


        :param sample_ids: The sample_ids of this SampleList.  # noqa: E501
        :type: list[str]
        """

        self._sample_ids = sample_ids

    @property
    def sample_list_id(self):
        """Gets the sample_list_id of this SampleList.  # noqa: E501


        :return: The sample_list_id of this SampleList.  # noqa: E501
        :rtype: str
        """
        return self._sample_list_id

    @sample_list_id.setter
    def sample_list_id(self, sample_list_id):
        """Sets the sample_list_id of this SampleList.


        :param sample_list_id: The sample_list_id of this SampleList.  # noqa: E501
        :type: str
        """
        if sample_list_id is None:
            raise ValueError("Invalid value for `sample_list_id`, must not be `None`")  # noqa: E501

        self._sample_list_id = sample_list_id

    @property
    def study_id(self):
        """Gets the study_id of this SampleList.  # noqa: E501


        :return: The study_id of this SampleList.  # noqa: E501
        :rtype: str
        """
        return self._study_id

    @study_id.setter
    def study_id(self, study_id):
        """Sets the study_id of this SampleList.


        :param study_id: The study_id of this SampleList.  # noqa: E501
        :type: str
        """

        self._study_id = study_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SampleList, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SampleList):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
