# coding: utf-8

"""
    cBioPortal web Public API [Alpha]

    A web service for supplying JSON formatted data to cBioPortal clients. Please note that this API is currently in beta and subject to change.  # noqa: E501

    OpenAPI spec version: 1.0 (beta). Backwards compatibility will be maintained (after 1.0 release)
    Contact: cbioportal@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Sample(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'unique_sample_key': 'str',
        'unique_patient_key': 'str',
        'sample_type': 'str',
        'sequenced': 'bool',
        'copy_number_segment_present': 'bool',
        'sample_id': 'str',
        'patient_id': 'str',
        'study_id': 'str'
    }

    attribute_map = {
        'unique_sample_key': 'uniqueSampleKey',
        'unique_patient_key': 'uniquePatientKey',
        'sample_type': 'sampleType',
        'sequenced': 'sequenced',
        'copy_number_segment_present': 'copyNumberSegmentPresent',
        'sample_id': 'sampleId',
        'patient_id': 'patientId',
        'study_id': 'studyId'
    }

    def __init__(self, unique_sample_key=None, unique_patient_key=None, sample_type=None, sequenced=None, copy_number_segment_present=None, sample_id=None, patient_id=None, study_id=None):  # noqa: E501
        """Sample - a model defined in Swagger"""  # noqa: E501
        self._unique_sample_key = None
        self._unique_patient_key = None
        self._sample_type = None
        self._sequenced = None
        self._copy_number_segment_present = None
        self._sample_id = None
        self._patient_id = None
        self._study_id = None
        self.discriminator = None
        if unique_sample_key is not None:
            self.unique_sample_key = unique_sample_key
        if unique_patient_key is not None:
            self.unique_patient_key = unique_patient_key
        if sample_type is not None:
            self.sample_type = sample_type
        if sequenced is not None:
            self.sequenced = sequenced
        if copy_number_segment_present is not None:
            self.copy_number_segment_present = copy_number_segment_present
        self.sample_id = sample_id
        self.patient_id = patient_id
        self.study_id = study_id

    @property
    def unique_sample_key(self):
        """Gets the unique_sample_key of this Sample.  # noqa: E501


        :return: The unique_sample_key of this Sample.  # noqa: E501
        :rtype: str
        """
        return self._unique_sample_key

    @unique_sample_key.setter
    def unique_sample_key(self, unique_sample_key):
        """Sets the unique_sample_key of this Sample.


        :param unique_sample_key: The unique_sample_key of this Sample.  # noqa: E501
        :type: str
        """

        self._unique_sample_key = unique_sample_key

    @property
    def unique_patient_key(self):
        """Gets the unique_patient_key of this Sample.  # noqa: E501


        :return: The unique_patient_key of this Sample.  # noqa: E501
        :rtype: str
        """
        return self._unique_patient_key

    @unique_patient_key.setter
    def unique_patient_key(self, unique_patient_key):
        """Sets the unique_patient_key of this Sample.


        :param unique_patient_key: The unique_patient_key of this Sample.  # noqa: E501
        :type: str
        """

        self._unique_patient_key = unique_patient_key

    @property
    def sample_type(self):
        """Gets the sample_type of this Sample.  # noqa: E501


        :return: The sample_type of this Sample.  # noqa: E501
        :rtype: str
        """
        return self._sample_type

    @sample_type.setter
    def sample_type(self, sample_type):
        """Sets the sample_type of this Sample.


        :param sample_type: The sample_type of this Sample.  # noqa: E501
        :type: str
        """
        allowed_values = ["Primary Solid Tumor", "Recurrent Solid Tumor", "Primary Blood Tumor", "Recurrent Blood Tumor", "Metastatic", "Blood Derived Normal", "Solid Tissues Normal"]  # noqa: E501
        if sample_type not in allowed_values:
            raise ValueError(
                "Invalid value for `sample_type` ({0}), must be one of {1}"  # noqa: E501
                .format(sample_type, allowed_values)
            )

        self._sample_type = sample_type

    @property
    def sequenced(self):
        """Gets the sequenced of this Sample.  # noqa: E501


        :return: The sequenced of this Sample.  # noqa: E501
        :rtype: bool
        """
        return self._sequenced

    @sequenced.setter
    def sequenced(self, sequenced):
        """Sets the sequenced of this Sample.


        :param sequenced: The sequenced of this Sample.  # noqa: E501
        :type: bool
        """

        self._sequenced = sequenced

    @property
    def copy_number_segment_present(self):
        """Gets the copy_number_segment_present of this Sample.  # noqa: E501


        :return: The copy_number_segment_present of this Sample.  # noqa: E501
        :rtype: bool
        """
        return self._copy_number_segment_present

    @copy_number_segment_present.setter
    def copy_number_segment_present(self, copy_number_segment_present):
        """Sets the copy_number_segment_present of this Sample.


        :param copy_number_segment_present: The copy_number_segment_present of this Sample.  # noqa: E501
        :type: bool
        """

        self._copy_number_segment_present = copy_number_segment_present

    @property
    def sample_id(self):
        """Gets the sample_id of this Sample.  # noqa: E501


        :return: The sample_id of this Sample.  # noqa: E501
        :rtype: str
        """
        return self._sample_id

    @sample_id.setter
    def sample_id(self, sample_id):
        """Sets the sample_id of this Sample.


        :param sample_id: The sample_id of this Sample.  # noqa: E501
        :type: str
        """
        if sample_id is None:
            raise ValueError("Invalid value for `sample_id`, must not be `None`")  # noqa: E501

        self._sample_id = sample_id

    @property
    def patient_id(self):
        """Gets the patient_id of this Sample.  # noqa: E501


        :return: The patient_id of this Sample.  # noqa: E501
        :rtype: str
        """
        return self._patient_id

    @patient_id.setter
    def patient_id(self, patient_id):
        """Sets the patient_id of this Sample.


        :param patient_id: The patient_id of this Sample.  # noqa: E501
        :type: str
        """
        if patient_id is None:
            raise ValueError("Invalid value for `patient_id`, must not be `None`")  # noqa: E501

        self._patient_id = patient_id

    @property
    def study_id(self):
        """Gets the study_id of this Sample.  # noqa: E501


        :return: The study_id of this Sample.  # noqa: E501
        :rtype: str
        """
        return self._study_id

    @study_id.setter
    def study_id(self, study_id):
        """Sets the study_id of this Sample.


        :param study_id: The study_id of this Sample.  # noqa: E501
        :type: str
        """
        if study_id is None:
            raise ValueError("Invalid value for `study_id`, must not be `None`")  # noqa: E501

        self._study_id = study_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Sample, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Sample):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
