# coding: utf-8

"""
    cBioPortal web Public API [Alpha]

    A web service for supplying JSON formatted data to cBioPortal clients. Please note that this API is currently in beta and subject to change.  # noqa: E501

    OpenAPI spec version: 1.0 (beta). Backwards compatibility will be maintained (after 1.0 release)
    Contact: cbioportal@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SampleFilter(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'sample_identifiers': 'list[SampleIdentifier]',
        'sample_list_ids': 'list[str]',
        'unique_sample_keys': 'list[str]'
    }

    attribute_map = {
        'sample_identifiers': 'sampleIdentifiers',
        'sample_list_ids': 'sampleListIds',
        'unique_sample_keys': 'uniqueSampleKeys'
    }

    def __init__(self, sample_identifiers=None, sample_list_ids=None, unique_sample_keys=None):  # noqa: E501
        """SampleFilter - a model defined in Swagger"""  # noqa: E501
        self._sample_identifiers = None
        self._sample_list_ids = None
        self._unique_sample_keys = None
        self.discriminator = None
        if sample_identifiers is not None:
            self.sample_identifiers = sample_identifiers
        if sample_list_ids is not None:
            self.sample_list_ids = sample_list_ids
        if unique_sample_keys is not None:
            self.unique_sample_keys = unique_sample_keys

    @property
    def sample_identifiers(self):
        """Gets the sample_identifiers of this SampleFilter.  # noqa: E501


        :return: The sample_identifiers of this SampleFilter.  # noqa: E501
        :rtype: list[SampleIdentifier]
        """
        return self._sample_identifiers

    @sample_identifiers.setter
    def sample_identifiers(self, sample_identifiers):
        """Sets the sample_identifiers of this SampleFilter.


        :param sample_identifiers: The sample_identifiers of this SampleFilter.  # noqa: E501
        :type: list[SampleIdentifier]
        """

        self._sample_identifiers = sample_identifiers

    @property
    def sample_list_ids(self):
        """Gets the sample_list_ids of this SampleFilter.  # noqa: E501


        :return: The sample_list_ids of this SampleFilter.  # noqa: E501
        :rtype: list[str]
        """
        return self._sample_list_ids

    @sample_list_ids.setter
    def sample_list_ids(self, sample_list_ids):
        """Sets the sample_list_ids of this SampleFilter.


        :param sample_list_ids: The sample_list_ids of this SampleFilter.  # noqa: E501
        :type: list[str]
        """

        self._sample_list_ids = sample_list_ids

    @property
    def unique_sample_keys(self):
        """Gets the unique_sample_keys of this SampleFilter.  # noqa: E501


        :return: The unique_sample_keys of this SampleFilter.  # noqa: E501
        :rtype: list[str]
        """
        return self._unique_sample_keys

    @unique_sample_keys.setter
    def unique_sample_keys(self, unique_sample_keys):
        """Sets the unique_sample_keys of this SampleFilter.


        :param unique_sample_keys: The unique_sample_keys of this SampleFilter.  # noqa: E501
        :type: list[str]
        """

        self._unique_sample_keys = unique_sample_keys

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SampleFilter, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SampleFilter):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
