# coding: utf-8

"""
    cBioPortal web Public API [Alpha]

    A web service for supplying JSON formatted data to cBioPortal clients. Please note that this API is currently in beta and subject to change.  # noqa: E501

    OpenAPI spec version: 1.0 (beta). Backwards compatibility will be maintained (after 1.0 release)
    Contact: cbioportal@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SampleMolecularIdentifier(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'sample_id': 'str',
        'molecular_profile_id': 'str'
    }

    attribute_map = {
        'sample_id': 'sampleId',
        'molecular_profile_id': 'molecularProfileId'
    }

    def __init__(self, sample_id=None, molecular_profile_id=None):  # noqa: E501
        """SampleMolecularIdentifier - a model defined in Swagger"""  # noqa: E501
        self._sample_id = None
        self._molecular_profile_id = None
        self.discriminator = None
        if sample_id is not None:
            self.sample_id = sample_id
        if molecular_profile_id is not None:
            self.molecular_profile_id = molecular_profile_id

    @property
    def sample_id(self):
        """Gets the sample_id of this SampleMolecularIdentifier.  # noqa: E501


        :return: The sample_id of this SampleMolecularIdentifier.  # noqa: E501
        :rtype: str
        """
        return self._sample_id

    @sample_id.setter
    def sample_id(self, sample_id):
        """Sets the sample_id of this SampleMolecularIdentifier.


        :param sample_id: The sample_id of this SampleMolecularIdentifier.  # noqa: E501
        :type: str
        """

        self._sample_id = sample_id

    @property
    def molecular_profile_id(self):
        """Gets the molecular_profile_id of this SampleMolecularIdentifier.  # noqa: E501


        :return: The molecular_profile_id of this SampleMolecularIdentifier.  # noqa: E501
        :rtype: str
        """
        return self._molecular_profile_id

    @molecular_profile_id.setter
    def molecular_profile_id(self, molecular_profile_id):
        """Sets the molecular_profile_id of this SampleMolecularIdentifier.


        :param molecular_profile_id: The molecular_profile_id of this SampleMolecularIdentifier.  # noqa: E501
        :type: str
        """

        self._molecular_profile_id = molecular_profile_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SampleMolecularIdentifier, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SampleMolecularIdentifier):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
