# coding: utf-8

"""
    cBioPortal web Public API [Alpha]

    A web service for supplying JSON formatted data to cBioPortal clients. Please note that this API is currently in beta and subject to change.  # noqa: E501

    OpenAPI spec version: 1.0 (beta). Backwards compatibility will be maintained (after 1.0 release)
    Contact: cbioportal@googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TypeOfCancer(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'dedicated_color': 'str',
        'short_name': 'str',
        'parent': 'str',
        'cancer_type_id': 'str'
    }

    attribute_map = {
        'name': 'name',
        'dedicated_color': 'dedicatedColor',
        'short_name': 'shortName',
        'parent': 'parent',
        'cancer_type_id': 'cancerTypeId'
    }

    def __init__(self, name=None, dedicated_color=None, short_name=None, parent=None, cancer_type_id=None):  # noqa: E501
        """TypeOfCancer - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._dedicated_color = None
        self._short_name = None
        self._parent = None
        self._cancer_type_id = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if dedicated_color is not None:
            self.dedicated_color = dedicated_color
        if short_name is not None:
            self.short_name = short_name
        if parent is not None:
            self.parent = parent
        self.cancer_type_id = cancer_type_id

    @property
    def name(self):
        """Gets the name of this TypeOfCancer.  # noqa: E501


        :return: The name of this TypeOfCancer.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this TypeOfCancer.


        :param name: The name of this TypeOfCancer.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def dedicated_color(self):
        """Gets the dedicated_color of this TypeOfCancer.  # noqa: E501


        :return: The dedicated_color of this TypeOfCancer.  # noqa: E501
        :rtype: str
        """
        return self._dedicated_color

    @dedicated_color.setter
    def dedicated_color(self, dedicated_color):
        """Sets the dedicated_color of this TypeOfCancer.


        :param dedicated_color: The dedicated_color of this TypeOfCancer.  # noqa: E501
        :type: str
        """

        self._dedicated_color = dedicated_color

    @property
    def short_name(self):
        """Gets the short_name of this TypeOfCancer.  # noqa: E501


        :return: The short_name of this TypeOfCancer.  # noqa: E501
        :rtype: str
        """
        return self._short_name

    @short_name.setter
    def short_name(self, short_name):
        """Sets the short_name of this TypeOfCancer.


        :param short_name: The short_name of this TypeOfCancer.  # noqa: E501
        :type: str
        """

        self._short_name = short_name

    @property
    def parent(self):
        """Gets the parent of this TypeOfCancer.  # noqa: E501


        :return: The parent of this TypeOfCancer.  # noqa: E501
        :rtype: str
        """
        return self._parent

    @parent.setter
    def parent(self, parent):
        """Sets the parent of this TypeOfCancer.


        :param parent: The parent of this TypeOfCancer.  # noqa: E501
        :type: str
        """

        self._parent = parent

    @property
    def cancer_type_id(self):
        """Gets the cancer_type_id of this TypeOfCancer.  # noqa: E501


        :return: The cancer_type_id of this TypeOfCancer.  # noqa: E501
        :rtype: str
        """
        return self._cancer_type_id

    @cancer_type_id.setter
    def cancer_type_id(self, cancer_type_id):
        """Sets the cancer_type_id of this TypeOfCancer.


        :param cancer_type_id: The cancer_type_id of this TypeOfCancer.  # noqa: E501
        :type: str
        """
        if cancer_type_id is None:
            raise ValueError("Invalid value for `cancer_type_id`, must not be `None`")  # noqa: E501

        self._cancer_type_id = cancer_type_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TypeOfCancer, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TypeOfCancer):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
